#101 [WIP] プロジェクトファイルのバージョン間マイグレーション
Hiroshiba/voicevox pull request #102
Opened 2021-08-16 01:03 UTC by Segu-g

プロジェクトファイルについての操作をstore内の`index.ts`からstore内の`store/project`フォルダに移し，`store/project/version0.3.0.ts` , `store/project/version0.4.0.ts`のようにプロジェクトファイルの形式を記述する構造にしてみました．
前後のバージョン間のプロジェクトファイルの変換関数(`updater`)を記述することでマイグレーションを実現しています．

2021-08-17 03:53 UTC, Segu-g commented
2021年8月17日現在　mainブランチにおいてソフトウェアのバージョンは0.3.1と設定されており、プロジェクト形式の更新バージョンを0.4.0としています。従って現在のmainブランチから生成されたプロジェクトフォルダは形式が不正となり、自身で読み込むことができません．
バージョン0.3.0 , 0.3.1のプロジェクトファイルは過去のリリースから作成したものを用い、バージョン0.4.0のプロジェクトファイルはmainブランチから作成したプロジェクトファイルに対してテキストエディタ等でappVersionを"0.3.1"から"0.4.0"に書き換えたものを使用してください。

2021-08-17 15:01 UTC, Hiroshiba commented
ソフトウェアのバージョンをプロジェクトファイルのバージョンにするとそういった煩わしさがあるんですね。なるほどです。
releaseブランチを切ってmainブランチのバージョンは先に上げておくか、プロジェクトファイルバージョンを別に作るか、といったところでしょうか・・・
hotfixが入ったときに強い設計にしておきたいのですが、どうすればいいでしょう。

2021-08-17 16:15 UTC, Hiroshiba requested changes
やりたいこと（プロジェクトファイルのマイグレーションを型レベルで保証する）はとてもかっこいいと思うのですが、ライブラリを管理するくらいの気合が必要な実装だと感じました。

このプルリクエストには0.3.1のプロジェクトファイルを0.4.0へマイグレーションする機能と、マイグレーションのインターフェースの機能が備わっていて、前者は急ぎたい一方、後者は議論が必要で時間がかかるかもしれません。
とりあえずマイグレーションするだけ（load時のバージョンが0.4.0未満ならcharactorをcharacterにreplaceする）のコードをマージして、後者はゆっくり実装していくのはどうでしょう。

2021-08-17 16:15 UTC, Hiroshiba commented on src/store/project/index.ts
> +        typeAssert<IsExact<typeof projectData, ProjectType>>(true);
後続の方が例えばaudioItemのキーを変更した場合、たぶんここでエラーが起きていることに気づくと思います。
そのとき、「プロジェクトファイルの型を変えれば良いんだな」ということがわかるような実装になっていると嬉しいです。

2021-08-17 17:56 UTC, Segu-g commented
ひとまず全てのバリデーションチェックを捨て，charactorIndexをcharacterIndexに書き換えるだけのコードをに差し替えました．
マイグレーションのコードはブランチを切ったのでissue等で議論しましょう．

2021-08-17 18:13 UTC, Hiroshiba reviewed
issueでの議論、良いと思います。
コードもすごくスッキリして良いと思います。　

2021-08-17 18:13 UTC, Hiroshiba commented on _typos.toml
> +
改行ミス？

2021-08-17 18:13 UTC, Hiroshiba commented on _typos.toml
> +extend-exclude = ["package-lock.json", "src/store/project.ts"]
ちなみにどの単語が引っかかりましたか？
たぶん単語ごとにexcludeする機能もあると思うので、そちらの設定をすると後続の人が楽かもしれません。

2021-08-17 18:25 UTC, Segu-g commented on _typos.toml
> +extend-exclude = ["package-lock.json", "src/store/project.ts"]
元々のプロジェクトファイルに`characterIndex`のtypoである`charactorIndex`が入り込んでいるためそれを参照する為に`charactor`が引っかかります．
`charactor`を単語に登録しても通りますが，typoを修正した意味が無くなると思ったのでファイルの除外としています．

2021-08-17 18:37 UTC, Hiroshiba commented on _typos.toml
> +extend-exclude = ["package-lock.json", "src/store/project.ts"]
なるほどです、よくわかりました。
バージョン1.0.0にするあたりで古くなったバージョンの互換性を失くしてしまっても良いかもしれませんね。

2021-08-17 18:38 UTC, Hiroshiba requested changes
先に入った https://github.com/Hiroshiba/voicevox/pull/114 が偶然コンフリクトしているようです。

2021-08-17 22:20 UTC, Hiroshiba reviewed
remove/addされた行数を比較して気づいたのですが、`projectSchema`が消えてValidationがなくなっていそうです

2021-08-18 11:15 UTC, Segu-g commented
意図を勘違いしていたようで申し訳ありません。
バージョン0.3.0と0.4.0のSchemaに対してバリデーションチェックを行いながら、0.3.0の時は0.4.0の型へのキャストを書くという事でしょうか？

2021-08-18 11:38 UTC, Hiroshiba commented
最新版になったものをバリデーションするのが良いのかな、と思っています。

最新版（0.4.0版）をロードした時
`json.load　→　validation`

0.3.1版をロードした時
`json.laod　→　migration　→　validation`

という感じです。

2021-08-18 14:17 UTC, merged