HelpWindowを廃止し、HelpDialogを実装
Hiroshiba/voicevox pull request #110
Opened 2021-08-16 18:16 UTC by MT224244

始めはvue-routerでルーティングする方法で実装を進めていましたが、Homeからページ遷移してしまうと戻った時に色々挙動がおかしくなることが分かったので、上に覆いかぶさる形でDialogでの実装になりました
これにより、vue-routerの存在意義が消えてしまいました

デメリットとして、ヘルプを開いている最中もキーボードショートカットが効いてしまうという問題があります

2021-08-16 18:17 UTC, MT224244 commented on src/store/ui.ts
> +      else commit(UNLOCK_UI);
どうせ見えなくなるので意味がないかもしれませんが、念のためDialog展開中はUIロックをかけています

2021-08-16 19:35 UTC, Hiroshiba requested changes
良い実装だと思いました。
vue-routerのchildrenを使った実装は変に煩雑になってしまったので、componentを切り替えるこちらの実装のほうが良い気がしました。

今回はとりあえずDialogですが、やはり理想的にはHomeとHelpは親子ではなく兄弟のほうが良い気がしています。
HomeからHelpに遷移してHomeに戻ったとき、どういった挙動が問題になったか知りたいです。

2021-08-16 19:35 UTC, Hiroshiba commented on src/components/HelpDialog.vue
> +            transition-next="fade"
ブラウザのタブ切り替えのように即座に切り替わるのが一般的かもしれません。

2021-08-16 19:35 UTC, Hiroshiba commented on src/store/ui.ts
> +      else commit(UNLOCK_UI);
isHelpDialogOpenが変化しなければcommitしない、というifを入れておくと良いかもしれないなと思いました

2021-08-17 00:08 UTC, MT224244 commented
> HomeからHelpに遷移してHomeに戻ったとき、どういった挙動が問題になったか知りたいです。

こんな感じでAudioCellが増えてInfoPaneとDetailPaneの動きがおかしくなりました
ぱっと見でこれはダメだなと判断して、Dialog方式に移行した次第です

https://user-images.githubusercontent.com/25514849/129643138-c725fa09-e6e2-4134-8e34-6b28bbef8cef.mp4

2021-08-17 17:21 UTC, Hiroshiba approved these changes
LGTM！　動画もありがとうございます、とてもわかりやすかったです。

2021-08-17 17:21 UTC, merged