メニュー，タイトルバーボタン，ウィンドウタイトルの統合
Hiroshiba/voicevox pull request #123
Opened 2021-08-19 04:17 UTC by madosuki

#104 

エンジンの起動中メッセージの箇所を移動してありますがこれはabsoluteで固定された要素を先に置いておくと，座標取得がおかしくなるのかわからないが他の要素にカーソル当てていても反応しなくなるからで，タイトルバーボタンをvue側に移した状態でこの問題に遭遇するとマウスで閉じられなくなるので移動させました．

統合したメニューバー，とりあえず，| アイコン | メニュー | タイトル | ボタン | 的な感じにしてあります．

2021-08-19 05:08 UTC, madosuki commented
isDevelopmentを見てフレームレスウィンドウするかどうかの処理を追加した．

2021-08-19 14:33 UTC, Hiroshiba requested changes
素晴らしいと思います！

背景によっては馴染んでしまうのが気になりました。簡単に枠だけを付ける方法をご存知だったりしますか？
![image](https://user-images.githubusercontent.com/4987327/130081078-116089b9-2369-451e-9bd4-c895c4e6272b.png)

（参考にVSCodeを見てみると、上・左・下を別の色にすることで枠感を出していました。）
![image](https://user-images.githubusercontent.com/4987327/130081506-d6f90b33-a0bf-44e5-90d5-7b833fd10bad.png)

2021-08-19 14:33 UTC, Hiroshiba commented on src/background.ts
> +ipcMain.handle("CLOSE_WINDOW", () => {
`ipcMain.handle`などで扱うkeyは、引数のミスを防止したり実装を簡単にしたい意図から、`src/type/ipc.d.ts`で型をつけるようにしています。
https://github.com/Hiroshiba/voicevox/blob/63d4bca6f9ba2f043d6ea287ff9678b5312f0d80/src/type/ipc.d.ts
こちらで型定義をお願いします。

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +    <img src="icon.png" id="windowLogo" alt="application logo" />
idやclassはkebab-caseでおねがいします。

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +    <div id="windowTitle text-center">VOICEVOX</div>
同上です

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +    <div id="windowTitle text-center">VOICEVOX</div>
text-centerは`class`だと思います。

idとclassがあるとどちらにしたか意識しないといけず少しコーディングがややこしくなりそうです。
他のコンポーネントと同じ用に、window-logoやwindow-titleもクラスにしてしまって、下のcss箇所を`.window-logo`などに変更すると良いと思います。

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +    <div id="windowTitle text-center">VOICEVOX</div>
タイトル文字がウィンドウの中央じゃないのがちょっと気になりました。

2021-08-19 14:33 UTC, Hiroshiba commented on src/background.ts
> +    win.restore();
`win.unmaximize()`というのがありそうです。
https://www.electronjs.org/docs/api/browser-window#winunmaximize

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +    <img src="icon.png" id="windowLogo" alt="application logo" />
quasarのq-imgを用いておくと後々変な挙動が起きづらくなるかもしれません。
https://github.com/Hiroshiba/voicevox/blob/63d4bca6f9ba2f043d6ea287ff9678b5312f0d80/src/components/AudioCell.vue#L23-L28

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/TitleBarButtons.vue
> +    ></q-btn>
最大化しているときはこのアイコンに変える、というのはどうでしょう。
![image](https://user-images.githubusercontent.com/4987327/130085600-31dadf0e-7a28-4e41-84d0-d4c4e176f3c5.png)

vue側の操作をelectron側に伝えつつ、状態を管理するのはuseGpuあたりが参考になるかもしれません。
https://github.com/Hiroshiba/voicevox/blob/63d4bca6f9ba2f043d6ea287ff9678b5312f0d80/src/store/ui.ts#L73

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/TitleBarButtons.vue
> +    Mousetrap.bind(["alt+f4", "ctrl+q", "command+q"], closeWindow);
ctrl+qで閉じるのは一般的じゃない（誤って閉じられる）かもしれません。

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/TitleBarButtons.vue
> +    Mousetrap.bind(["ctrl+m", "command+m"], minimizeWindow);
ctrl+mで最小化するのは一般的じゃないかもしれません。
（windowsはそもそもwin+↓で最小化できそうです。）

2021-08-19 14:33 UTC, Hiroshiba commented on src/components/TitleBarButtons.vue
> +.titleBarButtons {
kebab-case

2021-08-20 05:52 UTC, madosuki commented on src/background.ts
> +ipcMain.handle("CLOSE_WINDOW", () => {
型定義を行いました

2021-08-20 05:52 UTC, madosuki commented on src/components/MenuBar.vue
> +    <img src="icon.png" id="windowLogo" alt="application logo" />
windowLogoからwindow-logoに修正しました．

2021-08-20 05:53 UTC, madosuki commented on src/background.ts
> +    win.restore();
unmaximizeを使用する用に変更しました．

2021-08-20 05:54 UTC, madosuki commented on src/components/MenuBar.vue
> +    <img src="icon.png" id="windowLogo" alt="application logo" />
q-imgだとcssが上手く反映出来なかったのでとりあえずはimgで行きたいです．

2021-08-20 05:59 UTC, madosuki commented on src/components/TitleBarButtons.vue
> +    ></q-btn>
最大化時にアイコンを変える処理を追加しました．

createWindow関数内にmaximizeイベントとunmaximizeイベントのハンドラを記述し，storeで処理させるようにしました．

その時にplugins/ipcMessageReceiverPlugin.ts内のinstallのところにハンドラを追加しましたが問題ないでしょうか？

2021-08-20 05:59 UTC, madosuki commented on src/components/TitleBarButtons.vue
> +    Mousetrap.bind(["alt+f4", "ctrl+q", "command+q"], closeWindow);
外しました．

2021-08-20 06:00 UTC, madosuki commented on src/components/TitleBarButtons.vue
> +    Mousetrap.bind(["ctrl+m", "command+m"], minimizeWindow);
不要なので最小化ショートカットキーの定義を消しました．

2021-08-20 06:00 UTC, madosuki commented on src/components/TitleBarButtons.vue
> +.titleBarButtons {
修正しました．

2021-08-20 06:50 UTC, madosuki commented on src/components/MenuBar.vue
> +    <div id="windowTitle text-center">VOICEVOX</div>
absolute-centerで強制的に中央表示にできますがそうなるとウィンドウを縮小した時に重なってしまうので代わりにmargin-rightで調整するように修正しましたが他の環境でもちゃんと表示されるかよくわからず，この辺りは私のCSS力が足りないので私がなんとかするのは無理な気がします．

2021-08-20 07:07 UTC, madosuki commented
> 
> 
> 素晴らしいと思います！
> 
> 背景によっては馴染んでしまうのが気になりました。簡単に枠だけを付ける方法をご存知だったりしますか？
> ![image](https://user-images.githubusercontent.com/4987327/130081078-116089b9-2369-451e-9bd4-c895c4e6272b.png)
> 
> （参考にVSCodeを見てみると、上・左・下を別の色にすることで枠感を出していました。）
> ![image](https://user-images.githubusercontent.com/4987327/130081506-d6f90b33-a0bf-44e5-90d5-7b833fd10bad.png)

Electronのフレームレスウィンドウはbody辺りをcssでborderで指定してやると枠ができます．一応コミットに試しで入れてありますが，この辺りの調整よくわからないのでPRが通った後に好みに調整するのがいいんじゃないかなと思います．

![スクリーンショット 2021-08-20 160219](https://user-images.githubusercontent.com/4476489/130194167-8418b548-7d22-474a-b49b-09608820f811.png)

2021-08-20 10:00 UTC, madosuki commented
background.ts内のcreateWindow箇所にminWidthを追加して，なおかつMenuButton.vue無いの.q-badgeにoverflowを追加しました．
ウィンドウサイズの縮小に下限を設けないとクローズボタンが見えなくなったりするためその対策としてやりました．

2021-08-20 14:48 UTC, Hiroshiba reviewed
borderとタイトル中央寄せでぐっと良くなったように感じます！　すごく良いです。

2021-08-20 14:48 UTC, Hiroshiba commented on src/store/index.ts
> +    },
内部で用いているvuexライブラリの仕様なのですが、↓のような感じで`mutations`にstateを変更する関数を書いた後、
https://github.com/Hiroshiba/voicevox/blob/63d4bca6f9ba2f043d6ea287ff9678b5312f0d80/src/store/ui.ts#L45-L47

`actions`でそれを叩くようにしてみてください。
https://github.com/Hiroshiba/voicevox/blob/63d4bca6f9ba2f043d6ea287ff9678b5312f0d80/src/store/ui.ts#L71-L80

2021-08-20 14:48 UTC, Hiroshiba commented on src/views/Home.vue
> +  border-bottom: solid 4px #a4d4b4;
primaryカラーであれば、`global.$primary`にするとわかりやすそうです。

2021-08-21 01:04 UTC, madosuki commented on src/views/Home.vue
> +  border-bottom: solid 4px #a4d4b4;
global.$primaryに変更しました．

2021-08-21 01:06 UTC, madosuki commented on src/store/index.ts
> +    },
store/ui.ts内のmutationsとactionsにそれぞれDETECT_MAXIMIZEDとDETECT_UNMAXIMIZEDを実装しました．

2021-08-21 14:19 UTC, Hiroshiba approved these changes
LGTM！　ウィンドウがシュッとして良い感じになったと思います。

いただいたプルリクエストを見ていて、ロジックがわかり、GUI周りのことができ、かつ既存実装になじませるのが得意な方だと感じました。
ユーザーから要望がある[こちら](https://github.com/Hiroshiba/voicevox/issues/67)や、よくツイッターなどで言及されている問題である[こちら](https://github.com/Hiroshiba/voicevox/issues/16)などを任せたいと思ったのですが、いかがでしょうか。

2021-08-21 14:19 UTC, merged

2021-08-22 12:18 UTC, madosuki commented
今日追突事故に遭ってしまってムチ打ちの出方によっては多分しばらくコード書くどころじゃなくなくなるので申し訳ないですが辞退させてもらいます．
気分次第でコード書いてPR出すかもしれませんがその時はその時でよろしくお願いします．

2021-08-22 13:51 UTC, Hiroshiba commented
なんと・・・お大事になさってください。また機会があればぜひ・・・！