Undoヒストリが正しく積まれない/壊れる問題の修正
Hiroshiba/voicevox pull request #126
Opened 2021-08-19 16:39 UTC by mes51

#116 を他の方が担当されそうと言うことで、楽が出来るようこちらで直していた部分を上げておきます。
修正したのは、

* テキスト編集時、`v-model`でTwo-Wayバインディングされていたために`produceWithPatches`で返ってくるPatchが空になっていた問題の修正
* AudioCellの初期化処理で`FETCH_AUDIO_QUERY`をdispatchしていたためにRedoでセルの追加を戻すと以降のヒストリが消える(FETCH_AUDIO_QUERYによってヒストリが上書きされてしまう)問題の修正

の2点になります。

この修正により、一部動作が変わり、

* Enterを押したり、フォーカスを外さなくてもアクセントの生成が行われる
  * 逆にこれらの操作ではアクセントの生成は行われなくなる
* AudioCell追加時には`FETCH_AUDIO_QUERY`はdispatchされず、`setAudioText`の呼び出し、または`PUT_TEXTS`がdispatchされるまで`audioItem.value.query`は空のまま
  * `PUT_TEXTS`は最後にまとめて`FETCH_AUDIO_QUERY`をdispatchするように

となります。
使用感が若干変わるのと、AudioCell周りのUndo/Redoの実装の仕方が変わるため、逆に障害になりそうであればCloseしていただいて問題ありません

2021-08-19 16:40 UTC, mes51 commented on src/store/audio.ts
> +          addedAudioKeys.map((audioKey) =>
ここはUndo/Redoを行うことを考えるとPromise.allでまとめるのではなく、シーケンシャルに実行すべきかもしれません

2021-08-19 20:40 UTC, Hiroshiba commented
undo/redoにチャレンジされていたんですね、失礼しました。
せっかくなので、undo/redoのプルリクエストが来た際にレビュワーとして意見を求めるかもしれません。

ちなみに、undo/redoに取り組まれて課題だと感じられた箇所はありますか？
ぜひ知りたいなと思って伺ってみました。

2021-08-19 20:40 UTC, Hiroshiba reviewed
v-model部分の置換、onMount時の挙動修正は良いと思います。
onMountのところはなるほどと思いました。

throttleの部分をかなり悩んでいます。

たしかにエンターを押す手間は省けて嬉しいのですが、テキストを入力するたびにアクセントのUIが更新される（おそらくユーザーにとって意味がない）と、画面がちらついて微妙かもしれないなと思いました。
それと300msecの待機中に別操作をした場合（たとえばshift+enterの改行）、undoの順序が入れ替わりそうなのも気になります。
でも、setTextを何度も呼ぶことで「文字を確定したごとにundoされていく」という挙動にできるのは魅力的かもしれません。（実際undoを使ってみないと確実なことは言えませんが・・・。）

throttleはundo/redoが実装されてから、これらと絡めて再チャレンジするというのはどうでしょう。

2021-08-20 11:56 UTC, mes51 commented
こちらこそ、力量不足なまま大物に突っ込んでしまい申し訳ないです...

> ちなみに、undo/redoに取り組まれて課題だと感じられた箇所はありましたか？

まだ全体を見渡せていないため的外れになっているかもしれないですが、ヒストリに積まれるactionが複数のaction内から呼ばれており、ユーザーの操作という単位にまとめようとしたときに障壁になりそうだなと感じました。
このあたりは設計思想も絡んでくると思うので個人的な意見となりますが、Commandの単位をユーザーの操作の粒度にまで荒くし、Viewからしか呼ばないようにする、とした方がメンテナンスしやすいかなと考えています(このあたりは今までこの方式でしか実装したことがないというのもあり、邪道かもしれません

> throttleについて

確かに現状のPRの状態だと順番が入れ替わってしまう可能性がありますね...
ただ、throttleを外すとなると、こちらで思いつくのが

* 単純にthrottleを外す
  * 文字数が多くなる or スペックが低いPCで反応が悪くなる
* Enterで反映する形に戻す
  * Patchを正しく生成するために直接storeに反映できない関係上、テキストを変更した後、確定前にViewのステートが変わった場合(ex: マウスカーソルを乗せたり下ろしたりしたとき)にテキストが巻き戻ってしまう
    * reactiveな変数とのTwo-Wayバインディングにした上で、Enterを押されたタイミングでstoreに書き戻す&storeを監視して変更時に変数に反映する、とすれば回避可能と考えられるが、処理が複雑になる

となるかなと考えています。

2021-08-20 15:44 UTC, Hiroshiba commented
Commandをユーザー操作の粒度まで荒くし、viewからaction経由で実行するのは、ユーザー操作とcommandが1:1対応していることを意識しやすそうなので賛成です。
その場合はCommand ActionがQueueになるような実装を噛ませればうまく回るかもですね。

> 単純にthrottleを外す
> 文字数が多くなる or スペックが低いPCで反応が悪くなる

throttleはあってもなくても文字数は変わらないと思います。
`スペックが低いPCで反応が悪くなる`がちょっとわからなかったので詳しく聞きたいです。

> Enterで反映する形に戻す

updateのタイミングでだけsetTextActionを実行し、changeのタイミングでupdateAudioQueryを実行するというのはどうでしょう。
それをundoするのが難しそうな気もしますが、まあ一旦これで・・・。

2021-08-20 16:49 UTC, mes51 commented
> `スペックが低いPCで反応が悪くなる`がちょっとわからなかったので詳しく聞きたいです。

https://user-images.githubusercontent.com/936617/130266319-fc1a8a0c-9490-496a-9537-5a32cec1fa4c.mp4

これは極端な例ですが、1文字ずつ`FETCH_AUDIO_QUERY`、または`FETCH_ACCENT_PHRASES`を呼んだ例ですが、動画7秒くらいで文字を消したり、入力文字を切り替えているにもかかわらず、アクセントが前のテキストの入力分の処理が終わっておらず、現在の文のアクセントが表示されるまでに時間が掛かるような状態です。

これを回避するため、throttleを挟んで処理回数を減らす、という事をしていたが、それが無くなるので遅くなる、という話になります

2021-08-20 22:30 UTC, Hiroshiba commented
なるほど！エンジンのキューが溜まって遅延するんですね、すごくよくわかりました。
ローマ字入力する機会はほぼなさそうですが、テキストを消去するときにこうなりそうだなと思いました。

2021-08-20 22:33 UTC, Hiroshiba requested changes

2021-08-20 22:33 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +      console.log(text);
消し忘れかも？
```suggestion
```

2021-08-21 08:58 UTC, mes51 commented on src/components/AudioCell.vue
> +      console.log(text);
すいません、消し忘れです...

2021-08-21 14:57 UTC, Hiroshiba approved these changes
LGTM！
色んな所で実装が思想と乖離しているところがあると思うので、また気づいたらこうやって修正をもらえると嬉しいです。

2021-08-21 14:57 UTC, merged