[WIP] Feature/undo redo
Hiroshiba/voicevox pull request #138
Opened 2021-08-22 16:26 UTC by Segu-g

2021-08-30 09:42 UTC, Hiroshiba commented
@Segu-g レビューを始めてもよかったりしますか？👀

2021-08-30 16:23 UTC, Segu-g commented
スライダー周りの処理は #171 のほうで実装していただいているようなのでこちらではlabelを付けてlazyにするだけにしてあります。それ以外の部分はレビューして大丈夫です。しかし、このままではとても読みにくいと思うのでコメントは順次追加していこうと思っています。

2021-08-31 12:52 UTC, Hiroshiba reviewed
一通り眺めてみました。command周りのラッパーがちゃんと読めてませんが、今の段階で気づいたことをコメントしてみます。

2021-08-31 22:51 UTC, Segu-g commented on src/store/audio.ts
> +      ).catch(() => []);
FETCH処理でエラーが発生した場合にはwindow.electron.logErrorを叩くように変更しました。

2021-08-31 22:58 UTC, Segu-g commented on src/store/audio.ts
> +        query: await dispatch(GENERATE_INITIAL_AUDIO_QUERY, {}),
queryがoptionalだと処理が落ちる部分を修正し、初期化時または`FETCH_AUDIO_QUERY`が失敗する場合はqueryをundefinedにするようにしました。

2021-09-08 15:53 UTC, Segu-g commented
QuasarのSliderのバグだと思うのですがSliderが描画された初期状態で、尚且つスライダーの移動を短いクリックで行ったときにHover状態が保持されSliderに対してmodel-valueが反映されなくなります。Quasarに修正を加える必要があり致命的ではないため、このままレビューをお願いしたいのですがいかがでしょうか？

https://user-images.githubusercontent.com/51497552/132541868-54d7d655-38c9-4f4b-8a22-68786a4ece67.mp4

2021-09-08 18:25 UTC, Hiroshiba commented
一旦このままレビュー進めて良いと思います。

ただ、イントネーションやアクセントスライダーだとその現象が起こりやすいかもなので、可能であれば回避したいかもですね。
Quasarは割と更新されていそうなので、もしかしたらアップデートで直ったり・・・？

2021-09-09 09:17 UTC, Hiroshiba commented
やー超大作ですね！！　undo/redoはソフトウェアの夢です。　ぜひマージしたいです。
そのためにおそらく何度もいろいろお聞きすると思います。　頑張りましょう・・・！（何卒よろしくお願いします！）

2021-09-09 09:17 UTC, Hiroshiba commented
と、ちょっと眺めてみましたが、思った以上にレビューが難しそうでした。
といってもコード自体はまとまっていそうな印象を受けたので、どういう設計になっていて、それぞれどこで実行されているかが知れればかなり読めそうな気がしているのですが、説明頂いてもよろしいでしょうか・・・？👀

2021-09-09 09:57 UTC, Segu-g commented
1つのプルリクにするにはちょっとだけ大きかったかもしれませんね・・・
このプルリクでは1つの操作に対応するコマンドを通常のStoreである`audioStore`とは別の`audioCommandStore`中に作り、UNDO/REDO可能な操作は`audioCommandStore`の`actions`および`mutations`(ラベルが`COMMAND_`から始まる)を通して呼ぶことでUNDO/REDOの為に必要なoperationを記録しています。非同期な処理を含まないコマンドについてはactionからpayloadをそのままcommitし、mutation内で`audioStore`内のmutationを関数として呼び操作を記録するだけです。しかし、非同期処理を含むコマンドの場合は非同期にmutationを発行するとoperationの記録が複雑になるため、非同期的に取得する必要があるデータをactionで事前に取得し1つのmutationでコマンドが完結するようにしています。

2021-09-09 10:08 UTC, Segu-g commented
これを実現するために、`audioCommandStore`や`command.ts`以外にも多少の変更が入っています。例えば`AudioCell.vue`内の副作用で`AudioQuery`を更新していた箇所をなくしてtextの更新時に取得タイミングを変更したり、`FETCH_AUDIO_*`系でsetまでされていた箇所を単純にapiを叩くだけに変更したりしています。

2021-09-09 10:31 UTC, Hiroshiba commented
なるほどです！　ありがとうございます。　なんとなく理解できました。
今更ですが、１個ずつコマンドをマージしていったほうが良かったかもしれませんね・・・

2021-09-09 11:27 UTC, Hiroshiba requested changes
fetchの副作用が消されているの良いなと思いました！

差分もコメントもとんでもない量なので、もしかしたら切り分けて徐々にCOMMAND化していったほうがマージまで早いかもしれません。

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/audio.ts
> +      if (query !== undefined) {
throwでいいかも

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/audio.ts
> +        const newAccentPhrases: AccentPhrase[] = JSON.parse(
関係ないのですが、今思ったらこの処理がImmerの本業な気がしました。Immer使えるかも？

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/audio.ts
> +          return newAccentPhrases;
エラーの握りつぶし

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/audio.ts
> +          return newAccentPhrases;
同上

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/audio.ts
> +      if (query !== undefined) {
こっちもthrowで良いかもです

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/audio.ts
> +    ) => {
queryかaccentPhrasesを渡せるような引数にして、型で処理分ける手もあるなと感じました。
（draftだとうまく動かないかも）

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/command.ts
> -immer.setAutoFreeze(false);
なんか意図があってglobalのsetAutoFreezeではなくこっちを使った記憶がうっすらあります・・・
こっちのsetAutoFreeze+produceWithPatchesだとvueとimmerでバッティングしない、みたいなのあり得るかも・・・？

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/command.ts
> +        if (command != null) {
`if (command != null) {`が２つありそう

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/command.ts
> +        if (command != null) {
同上

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/project.ts
> +          commit(CLEAR_COMMANDS);
LOAD_PROJECT自体をUNDOできるとかっこいいかもしれません。

2021-09-09 11:27 UTC, Hiroshiba commented on src/store/command.ts
> +      JSON.parse(JSON.stringify(state)) as State,
ここが痛いですねー

2021-09-09 11:52 UTC, Segu-g commented on src/store/audio.ts
> +      window.electron.restartEngine();
コンフリ解消する時に見逃してしまったようです・・・
本当に申し訳ない🙇‍♀️🙇‍♀️🙇‍♀️

2021-09-09 12:21 UTC, Segu-g commented on src/store/audio.ts
> +          return [];
COMMAND_UPDATE_AUDIO_TEXTは`text`の更新とそれに追従する`query`、または`accenctPhrases`を更新しますがエラーで途中終了してしまうと`text`も更新されないようになってしまいます。　FETCH_ACCENT_PHRASESはtextが`""`(空文字列)だったり`"!?"`といった返り値が空リストとなるPOSTに対してエンジンがエラーを吐くようなので失敗した時の値を空リストにしています。

2021-09-09 13:32 UTC, Segu-g commented on src/store/type.ts
> +): Arg => arg;
プロパティの型を握りつぶさずにSroreOptions<State>として型付けする為の関数です。
as StoreOptions<State>として型を強制するとプロパティの型が消えてしまうのジェネリクスとextendsを使って型の条件付けをしています。

以下は最小化した [例](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQI4FcCGAbANCgDzAFMBjeAXzgDMoIQ4ByAARgE8SBaUgCx22IA7AObEAzgHp0MYNjGMAUAvYk4AFQCCAcTgBeOACUy0ACYAeMTCjAR+S9ZEA+ANxLSEQZbgriGsZp19Mw0oYThiAhghEzF1bUcACkxQgC44EOEASjSMvUc4ZOFXNw8vHxM1TDD9Hz8AhIQFODgAeQAFZAMNNQBJFoA5AH0B5DSAInbO7r6hkbHcJtaOrt6BwbUAdRbxyZWZ9a2xhSpMWPdPGEySi7h0QXLK6sRF3em1kZ3lt9n+5HmXr6rIabbZwCaA-Ygo4nWIBYo+QhRQQxMwAZXwany+lR4Ui0VhcAA-N4oOhiHA0tQcGJiPCOOTSKdxHo4ABtRYSABUcEWcG55zK9IqVTSjWafPFzSgxEwJg82DYSymQOGv0+yv2c1c4u5kulsvliteKpB6r2ayh2ua3Ioi05EkWyCIZBgZidSJRPgg1G8QseGPijgWzSdJHIbowODMXp9DyqADpjZrfvhwRr3r8xo4gxyJHABfA7nHhGkjO4oOZ7DZhHYrNXHI7neH3fjo-Tvbd7n6qgGtNn8I2w660FhsG2SB2i93hImIRnkKmk-Os0G4BI88goHQoAoALpAA) です。
```typescript
import { Equal, Expect } from '@type-challenges/utils'

type TAG = Record<string, string>;

const typeAsTAG = <Arg extends TAG>(arg: Arg): Arg => arg;


const typedTag = typeAsTAG({
  OPERATION_ONE: "OPERATION_ONE",
  OPERATION_TWO: "OPERATION_TWO"
} as const)

const untypedTag = {
  OPERATION_ONE: "OPERATION_ONE",
  OPERATION_TWO: "OPERATION_TWO"
} as TAG;

type Extends<S, T> = S extends T ? true : false;

type cases = [
  /* 
   * const typedTag: {
   *     readonly OPERATION_ONE: "OPERATION_ONE";
   *     readonly OPERATION_TWO: "OPERATION_TWO";
   * }
  */
  Expect<Extends<typeof typedTag, TAG>>,
  Expect<Equal<typeof typedTag.OPERATION_ONE, "OPERATION_ONE">>,
  // const untypedTag: Record<string, string>
  Expect<Extends<typeof untypedTag, TAG>>, 
  Expect<Equal<typeof untypedTag.OPERATION_ONE, "OPERATION_ONE">>, // Error
]
```

2021-09-09 13:45 UTC, Segu-g commented on src/store/audio.ts
> +          return undefined;
同上で、アクセント句が空リストになるようなテキストがPOSTされるとエラーが出るので、無効値のundefinedを返しています。

2021-09-09 13:55 UTC, Segu-g commented on src/store/project.ts
> +          commit(CLEAR_COMMANDS);
ここで想定しているUNDO/REDOはProjectのファイル回りの設定やファイル名まで含めた部分までを想定していますか？それともテキストのみに対する操作でしょうか？

2021-09-09 15:02 UTC, Hiroshiba commented on src/store/audio.ts
> +          return [];
なるほどです。エンジンが落ちているとテキストが更新できない、ということですよね。それはたしかに良くない挙動だと思います。
ただこの実装だと、エラーが起こったことがユーザーに伝わらず、それも同じくらい良くない挙動だと思います。

ちょっと実装は汚くなってしまうかもしれませんが、ここでerrorをthrowしてcatchし、setTextだけはcommitしたあと、次はvue側にerrorをthrowしてエラーが起きたこと知らせるのが良いかなと思いました。

2021-09-09 15:27 UTC, Hiroshiba commented on src/store/audio.ts
> +      payload: { audioKey: string; text: string } & (
普通の関数の処理を分離するかどうか問題＋タグを用意しないといけない、という感じでしょうか。
たしかにタグ増やさないといけないのは少し冗長ですね・・・

2021-09-09 15:38 UTC, Hiroshiba commented on src/store/type.ts
> +): Arg => arg;
なるほど！　とりあえず型を伝搬させているということでしょうか。　ちょっとわかった気がします！

2021-09-09 15:38 UTC, Hiroshiba commented on src/store/project.ts
> +          commit(CLEAR_COMMANDS);
テキストのみに対する操作を想定していましたが、たしかにユーザーが望む操作はより大規模ですね・・・
このままで良いと思いました。

2021-09-09 17:09 UTC, Segu-g commented on src/components/AudioCell.vue
> +    watch(
previewValueを使うと非同期通信の間は更新前の状態が見えてしまうのでBufferを使っていました。このように少しちらつきますがどうでしょうか。
https://user-images.githubusercontent.com/51497552/132730979-88da35fc-ac41-4233-ae42-0a952d281d10.mp4

2021-09-09 18:16 UTC, Segu-g commented on src/store/audio.ts
> +          const query: AudioQuery | undefined = isEngineReady
サーバーが落ちている時にFETCH_AUDIO_QUERYを呼ぶと、エラーが発生（timeout）するまでにおおよそ2sec程の間隔があります。複数の要素をfetchする事が考えられるこの部分で常にtimeoutを待つのは、ユーザーに長い待ち時間を取らせる事になり無駄です。

2021-09-09 18:27 UTC, Hiroshiba commented on src/store/audio.ts
> +          const query: AudioQuery | undefined = isEngineReady
なるほど！　たしかに仰るとおりだと思いました。
もしよければ後続の方のためにコメントを残して頂けると！

2021-09-09 18:46 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +    watch(
なるほどーー　さすがにこれは良くないですね。　Bufferで良いと思いました。

考えていて気づいたのですが、a→エンター→a→エンター→と高速に実行すると、audioQuery取得前のtextがsetされてロールバックしそうですね。
（やるやらないは置いておいて）解決策ってあったりしますか？

2021-09-10 08:04 UTC, Segu-g commented on src/components/AudioCell.vue
> +    watch(
debounceを挟むのがよくある方法ですかね　quasarのq-inputにもdebounceプロパティが存在し、(previewValueの議論で言及したwatchの欠点も同様に含んでいますが)bufferとほぼ同じことをしてくれます。
q-inputのdebounceはEnterで強制的に更新しちゃいますが@update:model-valueをdebounceでくるんで渡せばこの問題は解決できると思います。

2021-09-10 10:33 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +    watch(
なるほどです、たしかに高速で決定を繰り返すのを防ぐのはdebounceが有効そうに感じました。
もう一つ、確定後に入力したテキストがロールバックしてしまいそうなのも気になっています。こちらはどうでしょう…？

2021-09-10 10:46 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +    watch(
！　雑だけど解決策を思いつきました、previewValueにし、常にpreviewモードにする（viewに入力されているものを表示し続ける）のはどうでしょう。

2021-09-10 10:51 UTC, Segu-g commented on src/components/AudioCell.vue
> +    watch(
UNDO/REDOが実行されたときに、stateの変更を追従する方法が必要ですね

2021-09-10 10:55 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +    watch(
仰るとおりですね・・・。

2021-09-10 11:22 UTC, Segu-g commented on src/components/AudioCell.vue
> +    watch(
q-inputのdebounceの挙動として、debounceを用いて変更が蓄積されている場合はmodel-valueの変更を無視するようになっているようです。debounceの時間をcommandの反映時間より長くすれば、巻き戻る事は（commandの反映時間が遅れない限りは）無くなると思いました

2021-09-10 12:27 UTC, Segu-g commented on src/store/audio.ts
> +        return null;
undefinedに変更し、GET_AUDIO_CACHEと合わせていたと思われるGENERATE_AUDIOも修正しておきました。
(https://github.com/Hiroshiba/voicevox/pull/138/commits/d9562ae432632a27ab304fa84a4fb8f40f1d5c3c)

2021-09-10 15:48 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +    watch(
なるほど！いったんdebounceで良いと思いました！

2021-09-10 16:36 UTC, Segu-g commented on src/components/AudioDetail.vue
> +              :disable="query == undefined"
そうですね。@changeはenterかfocusが外れた時にされるので一旦フォーカスを外すかenterを押すかしないと再生ボタンが有効になりません。

2021-09-14 08:28 UTC, Segu-g commented
レビューで指摘された部分の修正が完了したので、このプルリクエストを閉じ細かく分けて再度投げたいと思います。

2021-09-14 08:28 UTC, closed without merging

2021-09-14 10:35 UTC, Hiroshiba commented
承知しました。お待ちしております・・・！