メニューにエンジン再起動の項目を追加
Hiroshiba/voicevox pull request #161
Opened 2021-08-26 07:11 UTC by madosuki

クライアントを落とさずにエンジンのみを再起動できるようになれば嬉しいかなと

2021-08-28 00:56 UTC, madosuki commented on src/background.ts
> +  if (engineProcess.exitCode) {
if elseやめてreturnするように変更したのと，nullかどうかで判別してること明示的にするために=== nullにしました．
あとコメントも付けました．
```TypeScript
  /*
    プロセスが生存している場合はexitCodeにnull，終了していればnumber型のexit codeが代入されています．
    プロセスが既に落ちている場合にtreeKillをわざわざ実行するのは違うかなと思いこうしてあります．
  */
  if (engineProcess.exitCode === null) {
    runEngine();
    return;
  }
```

2021-08-28 00:58 UTC, madosuki commented on src/background.ts
> +    treeKill(engineProcess.pid, (error) => {
```ipcMainHandle("RESTART_ENGINE", () => { ```内にイベントハンドラ処理を移しましたそれに伴って,
グローバル変数isRestartを削除しました．

あといくつかコメント加えました．

2021-08-28 00:59 UTC, madosuki commented on src/background.ts
> +    treeKill(engineProcess.pid, (error) => {
```RESTART```じゃなく```RESTART_AND_KILL_ENGINE```とか```KILL_THEN_RESTART_ENGINE```とかに変更した方がいいですか？

2021-08-28 15:47 UTC, Hiroshiba reviewed
ちょっと気になったところだけコメントしてみました。

2021-08-28 15:47 UTC, Hiroshiba commented on src/background.ts
> +    なので、ChildProcessのcloseイベントのタイミングで実行するようにしてあります。closeイベントはexitイベントよりも後に発火します。
`なので、ChildProcessのcloseイベントのタイミングで実行するようにしてあります。`は実装に書いてることと全く同じなので、書かなくても良いかもしれません。

2021-08-28 15:47 UTC, Hiroshiba commented on src/background.ts
> +      engineProcess.removeAllListeners("close");
コメント通り、再起動用に設定したclose listenerだけを削除するようにしたほうが良さそうに感じました。
というのも、engineProcessに付いている別のlistenerも消去されてしまう可能性があるためです。

2021-08-28 15:47 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +        store.dispatch(RESTART_ENGINE);
（細かいことですが）`restartEngineProcess`関数を呼ぶ処理と、`store.dispatch(RESTART_ENGINE)`を直接呼ぶ処理が混在しているので、どちらかに統一すると良いかもと思いました。

2021-08-28 15:48 UTC, Hiroshiba commented on src/background.ts
> +    treeKill(engineProcess.pid, (error) => {
`RESTART`は、`前のをKILLする`も意味に含まれていると感じるので、RESTARTだけでも簡潔でいいかなと思います。

2021-08-28 23:25 UTC, madosuki commented on src/background.ts
> +    treeKill(engineProcess.pid, (error) => {
ではそのままにしておきます．

2021-08-28 23:25 UTC, madosuki commented on src/background.ts
> +    なので、ChildProcessのcloseイベントのタイミングで実行するようにしてあります。closeイベントはexitイベントよりも後に発火します。
修正しました．

2021-08-28 23:29 UTC, madosuki commented on src/background.ts
> +      engineProcess.removeAllListeners("close");
removeListenerに変更しておきました．
```TypeScript
      engineProcess.removeListener("close", () => {
        return;
      });
```

2021-08-28 23:29 UTC, madosuki commented on src/components/MenuBar.vue
> +        store.dispatch(RESTART_ENGINE);
```restartEngineProcess```関数を呼ぶ方に統一しました．

2021-08-29 00:20 UTC, Hiroshiba requested changes

2021-08-29 00:20 UTC, Hiroshiba commented on src/background.ts
> +      engineProcess.removeListener("close", () => {
これだと消えないかも？
onceで指定したcallbackを一旦変数に入れて、ここにも渡す必要があるかもです。

2021-08-29 00:20 UTC, Hiroshiba commented on src/background.ts
> +     closeイベントはexitイベントよりも後に発火します。
スペース一個多いかもです（細かいですが気になってしまったので）
```suggestion
    closeイベントはexitイベントよりも後に発火します。
```

2021-08-29 00:30 UTC, madosuki commented on src/background.ts
> +      engineProcess.removeListener("close", () => {
変数に無名関数入れてlistener定義と削除時それを渡すように変更しました．

2021-08-29 00:30 UTC, madosuki commented on src/background.ts
> +     closeイベントはexitイベントよりも後に発火します。
修正しました．

2021-08-29 14:30 UTC, Hiroshiba approved these changes
LGTM！　いろいろ便利そうです。

2021-08-29 14:31 UTC, merged