Enable strict mode and extract component
Hiroshiba/voicevox pull request #171
Opened 2021-08-28 04:17 UTC by mes51

close: #153

開発時にVuexのstrictモードをONにするため、下記を行っています

* `v-model`でstoreを書き換えている部分を`model-value`に変更
* ピッチ、アクセントを別コンポーネントに切り出し

ピッチのコンポーネントに関しては、速度変更にも再利用できるよう汎用的な名前にしています

## TODO

-[x] strict mode on
-[x] ピッチ、アクセントのコンポーネントの切り出し
-[] AudioInfo内のパラメータのプレビュー対応
-[] engineStateの直接書き換え部分の修正(#161 マージ後)
-[] コンポーネント切り出しによるデザインの差異の有無の確認&修正

2021-09-01 17:57 UTC, Hiroshiba requested changes
いろんな知識が必要な難しい課題だったと思います。プルリクエストありがとうございます！

2021-09-01 17:57 UTC, Hiroshiba commented on src/components/AudioParameter.vue
> +    window.addEventListener("keyup", handleKeyPress);
このコンポーネントは大量に作成・破棄される可能性があるので、イベントはremoveしておいたほうがいいかもしれません。

2021-09-01 17:57 UTC, Hiroshiba commented on src/components/AudioAccent.vue
> +    window.addEventListener("keyup", handleKeyPress);
同上

2021-09-01 17:57 UTC, Hiroshiba commented on src/components/AudioAccent.vue
> +    const createAccentLine = () => {
`computed`でラップしておけば、vueが良い感じにキャッシュしてくれるかもしれません。

2021-09-01 17:57 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +                :disable="mora.pitch <= 0.0"
負の値がありえてしまうと誤解されそうなので、`mora.pitch == 0`で良いと思います。

2021-09-01 17:57 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +    };
`setPreviewValue`と`setPanning`も片方で良さそうに思います。
（たぶん同時にどちらも呼ばれてる・・・？）

2021-09-01 17:57 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +      previewAudioSpeedScale.isPreview = false;
これが必要になるタイミングがないかも？

2021-09-01 17:57 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +      return [previewObj, currentValue];
公開したい機能は「表示する値を返す」「プレビュー値を更新（しつつisPreview=true）」「プレビューを停止」だと思うので、こんな感じにかけそうかもしれません。
```ts
const isPreview = ref(false);
const previewValue = ref(undefined);
const setPreviewValue = (value) => {isPreview = true; previewValue = value};
const stopPreview = () => {isPreview = false};
const currentValue = computed(() => isPreview ? previewValue : storeValue);
return {currentValue, setPreviewValue, stopPreview};
```

2021-09-02 13:02 UTC, mes51 commented on src/components/AudioAccent.vue
> +    };
スライダ操作中にショートカットキーで再生、としたときなどに、`@change`が呼ばれず、正しくプレビュー状態が切り替わらなくなってしまうため、イベントハンドラとしては両方必要ですが、`isPreview`の制御は`setPanning`の中のみで良さそうです。

2021-09-02 13:02 UTC, mes51 commented on src/components/AudioParameter.vue
> +<template>
一応、他のパラメータが増えたとき(まだUIは決まっていないようですが、モーラ毎の速度等)に再利用可能なように汎用的な名前にしています。
ただ、スライダで設定するタイプがピッチのみになる見込みであればピッチ専用にしてしまっても良いかもしれません。

2021-09-02 13:07 UTC, mes51 commented on src/components/AudioDetail.vue
> +    const changeAccent = ([accentPhraseIndex, accent]: [number, number]) => {
`$emit`から渡ってくる引数の配列からバラすために、配列から分割代入しています。

....が、これは`$emit`から来る引数が配列に入ってくる、という勘違いによるもので、実際は`$emit`でイベントハンドラの引数を配列で渡してしまっているのが原因でした(普通に可変長引数として渡せば良かった)。
なので、普通に引数として書くように修正します

2021-09-02 13:14 UTC, mes51 commented on src/components/AudioInfo.vue
> +};
AudioAccentやAudioParameterでは、ここまで複数の要素は不要&適用してもあまり綺麗にならず、今のところここでしか使用しないため一旦ここに定義を書いています。
他の箇所でもプレビュー変数を利用するケースが出てきたときにどこかに括り出す、で良いかなと考えていますがいかがでしょうか?

2021-09-02 13:26 UTC, mes51 commented on src/components/AudioInfo.vue
> +      return [previewObj, currentValue];
なるほど。こちらの方がすっきりしそうです。
ただ、`setPanning`でpreview変数の値を現在のstoreの値に戻してあげる必要がある(そうしないと、`@change`が呼ばれなかった時にisPreviewがtrueになったタイミングで一瞬だけ前のpreview値にthumbが飛んでいく)ため、`setPreviewValue`の中で`isPreview = true`するのではなく、`startPreview`的な関数を追加する感じになりそうです

2021-09-02 15:55 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +      return [previewObj, currentValue];
`startPreview`の方が機能が分かれていてきれいなので、そちらの方が良いと思います！

2021-09-03 15:35 UTC, Hiroshiba commented on src/components/AudioParameter.vue
> +<template>
なるほど！　良いと思います。

2021-09-03 15:46 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +        :model-value="currentAudioIntonationScale"
`previewAudioIntonationScale`から別途`currentAudioIntonationScale`を定義するのも良さそうですが、定義だけで文字数が多くねって大変なので、`previewAudioIntonationScale.currentValue`を直接参照するというのはどうでしょう。

2021-09-03 15:46 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +};
今複数箇所でプレビュー変数を利用し始めてるのでくくりだしてもいいかなと思いました。
が、綺麗にならないなら、まあ別にいいかなとも思いました！

2021-09-03 15:52 UTC, Hiroshiba commented on src/components/AudioAccent.vue
> +    const createAccentLine = computed(() => {
computedはgetterなので、createにちょっと違和感がありました。
createをなくしちゃってaccentLineにするとスマートかもしれません。

2021-09-03 16:35 UTC, mes51 commented on src/components/AudioInfo.vue
> +        :model-value="currentAudioIntonationScale"
`previewAudioIntonationScale.currentValue`で最初試していたのですが、こうすると、なぜか`:model-value`であるにもかかわらず、setterが呼ばれる(そしてcurrentValueはcomputedのためsetterが無く、値の変更が出来ない)、という問題があったため、currentValueのみを別の変数にしていました。
ただ、改めて確認したところ、`previewAudioIntonationScale.currentValue.value`とすると問題ないようなので、こちらに変更します

2021-09-03 16:38 UTC, mes51 commented on src/components/AudioInfo.vue
> +};
なるほど。型定義だけ外に持って行っても、という感じでしたが`createPreviewValue`の中身ごと外に出せれば上手くまとめられそうなので、ちょっと試してみます

2021-09-04 12:14 UTC, mes51 commented
PreviewableValueをAudioInfoの外に括りだしてAudioAccent/AudioParameterでも利用するようにしましたが、置き場所について、今のところこういったものの置き場所がないようだったので、`src/helper`ディレクトリを作成してそちらに置きました。
これについて、他に良い置き場所があればご教示いただけると助かります

2021-09-04 12:34 UTC, Hiroshiba commented
camelCaseが良いようです。
https://typescript-jp.gitbook.io/deep-dive/styleguide#filename

2021-09-05 06:39 UTC, Hiroshiba reviewed
おっと、肝心のstrictモードへの変更が入っていないかもしれません。

2021-09-05 07:50 UTC, mes51 commented
https://github.com/Hiroshiba/voicevox/pull/171/files#diff-6617a8982092b70693d565d280deb361a2c860ca52f2a1d23f537ce5d276023bR78
以外にも入れる必要がある箇所がある、ということでしょうか?

(一応、`v-model`でstoreを直接書き換るとエラーが出るようにはなっているようです)
![image](https://user-images.githubusercontent.com/936617/132119380-afd2ed7e-f61f-4bf9-89da-4e11deabfd79.png)

2021-09-05 09:03 UTC, Hiroshiba commented
あ！　すみません、問題なさそうです！（検索漏れしていました。）

コンフリクトが起こっているようです。

2021-09-05 11:23 UTC, Hiroshiba approved these changes
LGTM！　お疲れさまでした！

VOICEVOXのコードはちょっとずつ複雑度が上がっているので、コードを整理するプルリクエストはとても助かります。
気になる点があればどんどんissueを建てていただければ・・・！

2021-09-05 11:24 UTC, merged