予期しないエラーをログファイルに書き出す
Hiroshiba/voicevox pull request #172
Opened 2021-08-28 13:07 UTC by k-kuroguro

#32 

予期しない(uncaught/unhandled)エラーが発生した場合、ログファイルに書き出します。(%USERPROFILE%\AppData\Roaming\VOICEVOX\logs\{filename}.log)

エラー発生時、ユーザにログファイルを送ってもらうことで特定しやすくなると思います。エラーが起きたらダイアログにエラー内容を表示する方法のほうがユーザがフィードバックを送りやすいと思いましたが、UIが苦手なので以上の内容にしました。
マージされたら、ダイアログ表示のissueも立てておきます。

2021-08-28 16:48 UTC, Hiroshiba reviewed
ソフトウェアプロセス・DOMどちらのエラーも記録できて良さそうに感じました！

2021-08-28 16:48 UTC, Hiroshiba commented on src/main.ts
> +import "source-map-support/register";
ちなみにこれってどういう効果があるんでしょう 👀

2021-08-28 16:48 UTC, Hiroshiba commented on src/components/ErrorBoundary.vue
> +  <slot></slot>
`ErrorBoundary.vue`はviewを持たないので、コンポーネントとしないほうが良いかもしれません。
vuexにlogをinitializeするactionを持たせるというのはどうでしょう。

2021-08-28 16:48 UTC, Hiroshiba commented on src/components/ErrorBoundary.vue
> +    this.info = info;
`info`や`instance`はどこにも使われていないかも？

2021-08-28 16:55 UTC, k-kuroguro commented on src/main.ts
> +import "source-map-support/register";
標準ではエラーのスタックトレースがミニファイされたものになっているので、このライブラリでソースマップを使って変換しています。

2021-08-28 17:08 UTC, k-kuroguro commented on src/components/ErrorBoundary.vue
> +  <slot></slot>
vueはエラー発生時、エラーを親コンポーネントに渡していき、最終的には`Vue.config.errorHandler`へと投げられます。
今回の実装では、ErrorBoundaryコンポーネントで伝播は止まりますが、vuexを使うと`Vue.config.errorHandler`まで到達します。
その際、`Vue.config.errorHandler`を使うほかのライブラリと干渉した経験があるので、コンポーネントを定義しています。(今は干渉するようなライブラリは入っていませんが、一応)

2021-08-28 17:15 UTC, k-kuroguro commented on src/components/ErrorBoundary.vue
> +    this.info = info;
すみません、消し忘れです。 修正しました。

2021-08-28 17:33 UTC, k-kuroguro commented on src/components/ErrorBoundary.vue
> +  <slot></slot>
自分は最終的にエラーはvueでユーザに通知したいと考えていて、その際には`ErrorBoundaty.vue`にviewを実装するのが一番いいと思い、この実装にしました。(error boundaryはreactの考え方?でreact製のものではそうなっていることが多いです。e.g.https://github.com/codesandbox/codesandbox-client/blob/389073613e06eee944231f4aeef9dfa746c1b947/packages/app/src/app/pages/common/ErrorBoundary/ErrorBoundary.tsx)

2021-08-28 20:15 UTC, Hiroshiba commented on src/main.ts
> +import "source-map-support/register";
ほー、なるほどです。

2021-08-28 20:31 UTC, Hiroshiba commented on src/components/ErrorBoundary.vue
> +  <slot></slot>
なるほど、フォールバックもできるんですね。よくわかりました。

2021-08-28 20:35 UTC, Hiroshiba commented on src/components/ErrorBoundary.vue
> +    error: Error | null;
this.errorは（viewが無い今はまだ）なくても良さそうです。

2021-08-28 20:35 UTC, Hiroshiba commented on src/components/ErrorBoundary.vue
> +  errorCaptured(error) {
他のコンポーネントは全てそうなっているので、Vue3のCompositoin APIの形式で書くのはどうでしょう。
ライフサイクルフックを全てon～にして`setup()`内に移せばいけそうです。
https://v3.ja.vuejs.org/api/composition-api.html#lifecycle-hooks

`this.`が全て消せると思います。

2021-08-29 04:17 UTC, k-kuroguro commented
Compositoin API形式で書き直しました。

2021-08-29 18:58 UTC, Hiroshiba requested changes
修正ありがとうございます。
https://github.com/Hiroshiba/voicevox/pull/161 とコンフリクトしているようです。

2021-08-29 20:16 UTC, k-kuroguro commented
コンフリクト解消しました。

2021-08-30 04:52 UTC, Hiroshiba reviewed
vuexとかのコード内に`console.error`がいくつかありそうです。
せっかくなのでこれらもログファイルに流すのもいいかなと思いました。

2021-08-30 04:52 UTC, Hiroshiba commented on src/background.ts
> +    ("00" + d.getDate()).slice(-2);
コメント（日時）と実装（日にち）が違っていそうです。
個人的にはエラー再現時にログが簡潔になりそうなので、日時に合わせるのが良いのかなと思いました。

2021-08-30 04:52 UTC, Hiroshiba commented on src/background.ts
> +ipcMainHandle("CAPTURE_ERROR", (_, { stack }) => {
細かいですが、この関数はエラーをキャプチャーするというより、エラーをログに書き出しているので、LOG_ERRORとかWRITE_ERROR_LOGとかが良いのかなと思いました。

2021-08-30 06:23 UTC, k-kuroguro commented
以下のように変更しました。
 - `CAPTURE_ERROR` => `LOG_ERROR`
 - vuex内のエラーハンドリングでは、型付けが難しそう(catch節には型がない)だったので、`LOG_ERROR`の型を緩めました
 - ログファイル名のフォーマットを`YYYYMMDD_hhmmss_error.log`に変更

2021-08-30 14:35 UTC, merged