リロードのショートカットキーを無効にする
Hiroshiba/voicevox pull request #185
Opened 2021-09-01 11:57 UTC by k-kuroguro

#183 

見えていませんがelectronのメニューが存在しているため、そのショートカットキーが機能しているようです。
メニューを明示的に削除することで、リロードはできなくなります。

2021-09-01 16:23 UTC, Hiroshiba requested changes

2021-09-01 16:23 UTC, Hiroshiba commented on src/background.ts
> +  win.removeMenu();
開発時はあると嬉しいので残しておきたいかもしれません。
昔はこんな感じでメニューを排除してたっぽいです。
https://github.com/Hiroshiba/voicevox/blob/18de6bbec4d6966fca607c5dd92feb7e48f842df/src/background.ts#L114-L117

2021-09-02 09:32 UTC, k-kuroguro commented on src/background.ts
> +  win.removeMenu();
開発時のみメニューを残すようにしました

2021-09-02 15:21 UTC, Hiroshiba commented on src/background.ts
> +  win.removeMenu();
`Menu.setApplicationMenu(null); `にするとwindow作成時から機能が除外されていて、
`removeMenu`だとメニュー付きでwindowが作成された後に除外することになりそうです。
メニュー付きで起動するとどれくらい起動が遅くなるのかわかりませんが、念の為に前者にしておきたいかもしれません。
（現状でメニュー付きで起動していてもそんなに遅いと感じないので、どちらでも良いかなとも思います）

2021-09-02 16:03 UTC, k-kuroguro commented on src/background.ts
> +  win.removeMenu();
おっしゃる通りですね。修正しました。

2021-09-02 17:08 UTC, Hiroshiba approved these changes
LGTM！　素早い対応ありがとうございます。

2021-09-02 17:08 UTC, merged