再生と保存時のエラーハンドリングの追加
Hiroshiba/voicevox pull request #189
Opened 2021-09-03 11:28 UTC by madosuki

#16

2021-09-03 11:33 UTC, madosuki commented
メニューでの一括音声書き出しの処理でPromise.allが使われているので途中で処理を抜けるのが難しいのでこれは処理が終わった後にArray<SaveCommandResult>な返り値を見て，
エラーがあれば結果をQuasarダイアログを出して，エラーが無ければ特に表示しないという感じになっています．

![スクリーンショット 2021-09-03 133459](https://user-images.githubusercontent.com/4476489/131998853-7e56bc63-a4ce-45dc-9d18-6ce341c81bfb.png)

2021-09-03 17:36 UTC, Hiroshiba requested changes
（個人的には）待望の機能です！！

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +          message: "再生に失敗しました。",
基本的に、ユーザーはエラーが発生したことも知りたい一方で、次に何をすればいいかも知れると喜ぶと思います。
タイトルを「再生に失敗しました」、メッセージを「エンジンの再起動をお試しください。」にするのはどうでしょう。

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +          title: "Result",
```suggestion
          title: "書き出しに失敗しました",
```

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +            msg = "書き込みエラーによって失敗しました。";
ここはなんて案内すればいいか思いつきませんでした。。

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +            msg = "エンジンエラーによって失敗しました。";
```suggestion
            msg = "エンジンのエラーによって失敗しました。エンジンの再起動をお試しください。";
```

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/HeaderBar.vue
> +          message: "再生に失敗しました。",
ここって生成＆再生でしたっけ。であれば
```suggestion
          message: "エンジンの再起動をお試しください。",
```

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/HeaderBar.vue
> +          title: "Error",
```suggestion
          title: "再生に失敗しました",
```

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +              const result: Array<[SaveCommandResult, string]> =
別にこのままでも良いのですが、もし可能なら２番めがパスであることがわかるようにresultとpathのobjのarrayにすると良いかもしれません。

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/SaveAllCommandResultDialog.vue
> +            <div class="error">書き込みエラー:</div>
失敗（書き込みエラー）みたいにして、失敗であることを明示すると優しいかもしれません。

2021-09-03 17:36 UTC, Hiroshiba commented on src/components/SaveAllCommandResultDialog.vue
> +            <div class="success">成功:</div>
成功を上に表示すると、全部成功したと勘違いするユーザーがいるかもしれないので、エラーを上にするのはどうでしょう。

2021-09-03 17:36 UTC, Hiroshiba commented on src/store/audio.ts
> +            return "WRITE_ERROR";
これは提案ではなく議論なのですが、`Result`をreturnするのと、errorをthrowするのって、どっちがいいんでしょう・・・。
エラーハンドリングをしたことがなく。。

2021-09-03 17:36 UTC, Hiroshiba commented on src/store/audio.ts
> +            if (state.isSaveAll) {
常にファイルパスも返すようにすれば、`isSaveAll`を消せてstateも１つ減るかも？

2021-09-03 17:36 UTC, Hiroshiba commented on src/store/audio.ts
> +            return false;
ドキュメントが無いので伝わりづらいのですが、この関数は「音声が再生されきったらtrue、途中でユーザー操作によりpauseされたらfalse」を返します。
ここの処理はおそらく「エラーが起きたらfalse」だと思うので、返り値の意味がコンフリクトしていそうです。

2021-09-04 01:23 UTC, madosuki commented on src/components/AudioDetail.vue
> +          message: "再生に失敗しました。",
修正しました．

2021-09-04 01:23 UTC, madosuki commented on src/components/AudioDetail.vue
> +          title: "Result",
修正しました．

2021-09-04 01:23 UTC, madosuki commented on src/components/AudioDetail.vue
> +            msg = "書き込みエラーによって失敗しました。";
```"書き込みエラーによって失敗しました。可能性としては書き込み先のストレージの容量不足または書き込み権限が無いことが考えられますご確認ください。"```
にしておきました．

2021-09-04 01:23 UTC, madosuki commented on src/components/AudioDetail.vue
> +            msg = "エンジンエラーによって失敗しました。";
修正しました．

2021-09-04 01:24 UTC, madosuki commented on src/components/HeaderBar.vue
> +          message: "再生に失敗しました。",
修正しました．

2021-09-04 01:25 UTC, madosuki commented on src/components/SaveAllCommandResultDialog.vue
> +            <div class="error">書き込みエラー:</div>
修正しました．

2021-09-04 01:25 UTC, madosuki commented on src/components/SaveAllCommandResultDialog.vue
> +            <div class="success">成功:</div>
エラーを上にしました．

2021-09-04 01:26 UTC, madosuki commented on src/store/audio.ts
> +            if (state.isSaveAll) {
そうするようにしました．

2021-09-04 01:26 UTC, madosuki commented on src/store/audio.ts
> +            return false;
```throw new Error()```にしてtry catchでやるように変更しました．

2021-09-04 01:30 UTC, madosuki commented on src/store/audio.ts
> +            return "WRITE_ERROR";
Prmoise.allの結果を配列で欲しいとかでなければTypeScriptではthrowでも良い気がします．
RustのようにResult型があれば話は違ってくるんでしょうが．
とりあえずPLAYの部分はpause処理の兼ね合いもあってthrowの方が適当であると思い直してthrowを使うように変更しておきました．

2021-09-04 07:12 UTC, Hiroshiba requested changes
ほぼほぼOKだと思いました！

2021-09-04 07:12 UTC, Hiroshiba commented on src/components/HeaderBar.vue
> +          title: "連続再生エラー",
```suggestion
          title: "再生に失敗しました",
```

2021-09-04 07:12 UTC, Hiroshiba commented on src/store/type.ts
> +  isSaveAll: boolean;
もう使われていないかも？

2021-09-04 07:12 UTC, Hiroshiba commented on src/store/audio.ts
> +        return ["DID_NOT", ""];
CANCELEDだと意図が伝わりやすいかもしれません。
あと`if (!blob) {`と同様、先にundefinedのときの処理を書くと更に見通しが良くなるかもしれません。

2021-09-04 07:12 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +              const result: Array<[SaveCommandResult, string]> =
あ、`Command`には別の意味（Undo/Redo用のCommand）をもたせてしまっているので、避けて頂けると助かります。

2021-09-04 09:33 UTC, madosuki commented on src/components/AudioDetail.vue
> +              "書き込みエラーによって失敗しました。可能性としては書き込み先のストレージの容量不足または書き込み権限が無いことが考えられますご確認ください。";
修正しました．

2021-09-04 09:33 UTC, madosuki commented on src/components/HeaderBar.vue
> +          title: "連続再生エラー",
修正しました．

2021-09-04 09:33 UTC, madosuki commented on src/store/type.ts
> +  isSaveAll: boolean;
消しておきました．

2021-09-04 09:36 UTC, madosuki commented on src/store/audio.ts
> +        return ["DID_NOT", ""];
```await window.electron.showAudioSaveDialog```直後に処理を持っていきました．

2021-09-04 09:37 UTC, madosuki commented
```SaveAllComanndResult```から```SaveAllResult```にファイル名とコンポーネント，型を変更しました．

2021-09-04 09:38 UTC, madosuki commented on src/components/HeaderBar.vue
> +          title: "Error",
修正しました．

2021-09-04 09:52 UTC, madosuki commented on src/components/MenuBar.vue
> +              const result: Array<[SaveCommandResult, string]> =
```export type SaveResultObject = { result: SaveResult; path: string | undefined };```を定義してこっちを使うように変更しました．
Commandを名称から外しておきました．

2021-09-04 11:54 UTC, Hiroshiba requested changes
実際にUI見てみて気になったところをコメントしてみました

2021-09-04 11:54 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +          message: msg,
実際にUIを見てみました。ボタンの文字色を黒に変えられそうでしょうか。
https://github.com/Hiroshiba/voicevox/blob/28dad280e129254f1063a73d85b3d67e33a6b8e1/src/components/SettingDialog.vue#L161

2021-09-04 11:54 UTC, Hiroshiba commented on src/components/SaveAllResultDialog.vue
> +          <q-toolbar-title>音声書き出し結果</q-toolbar-title>
緑背景に白文字が見づらいので、こちらも`secondary`にしていただけると！
（あと閉じるボタンも）

2021-09-04 12:26 UTC, madosuki commented on src/components/AudioDetail.vue
> +          message: msg,
変更しました．

2021-09-04 12:26 UTC, madosuki commented on src/components/SaveAllResultDialog.vue
> +          <q-toolbar-title>音声書き出し結果</q-toolbar-title>
変更しました．

2021-09-05 01:53 UTC, madosuki commented
カスタムコンポーネントにonHideDialogを使用しているとダイアログ終了時に```'unmount' property is null```エラーを出すので```SaveAllResultDialog.vue```からonHideDialogを削除しました．使っていなかった部分なので処理上問題ありません．

2021-09-05 02:22 UTC, madosuki commented
閉じるの位置を中央にしてみました．
![スクリーンショット 2021-09-05 111803](https://user-images.githubusercontent.com/4476489/132112777-c6f02b44-eb08-4a9c-a071-dde72ad988f7.png)

2021-09-05 06:30 UTC, Hiroshiba requested changes

2021-09-05 06:30 UTC, Hiroshiba commented on src/store/type.ts
> +  isSaveAllResultOpen: boolean;
使われてないかも？

2021-09-05 06:30 UTC, Hiroshiba commented on src/components/SaveAllResultDialog.vue
> +        <q-item clickable v-ripple align="center" @click="close">
他の（エンジンモード変更とかの）ダイアログ右下に閉じるだったので、合わせておいたほうが良いかもです。
それと、この見た目だったら「ヘルプ」ボタンと同様に白ボタンにしたいかもしれません。

2021-09-05 06:48 UTC, madosuki commented on src/store/type.ts
> +  isSaveAllResultOpen: boolean;
消しました．

2021-09-05 06:50 UTC, madosuki commented on src/components/SaveAllResultDialog.vue
> +        <q-item clickable v-ripple align="center" @click="close">
位置を戻して，白ボタンにしました．
ついでに```q-toolbar```と```q-btn```に変更しましたが，これは前の実装だとフッター全体がボタンになってしまっていたからです．確認不足でした．

2021-09-05 07:04 UTC, Hiroshiba commented
LGTM！　とうとう再生エラーダイアログを表示できる・・・！👏

2021-09-05 07:04 UTC, Hiroshiba approved these changes

2021-09-05 07:04 UTC, merged