プロジェクトの新規作成をメニューに追加する
Hiroshiba/voicevox pull request #202
Opened 2021-09-08 12:47 UTC by HyodaKazuaki

close #200

# 概要

ファイルメニューに「新規作成」メニューを追加します。

開いているプロジェクトに変更があるか否か判定する方法がわからなかったため、どのような場合でも警告のダイアログが表示されます。
実装は「プロジェクトを開く」メニューを参考にさせていただきました。 ref. #11 

# 挙動

![TJNNMRV](https://user-images.githubusercontent.com/17569894/132510652-bc773a1b-4514-4549-9bf9-1a47c66cf154.gif)

# 議論

* タイトルの左に不自然なハイフンが表示される
空のプロジェクトを開く方法をとっているため、`SET_PROJECT_FILEPATH`に空白を与えています。
タイトルの左にプロジェクト名(i.e. 空白)が表示されて、結果的にタイトル左にハイフンのみが表示されてしまいます。

2021-09-08 17:48 UTC, Hiroshiba reviewed
このままMenuBarに処理を書いても問題はないのですが、もしよかったらプロジェクトファイル系の処理が書いてある場所にまとめるというのはどうでしょう。
`SAVE_PROJECT_FILE`辺りが参考になるかもしれません。
https://github.com/Hiroshiba/voicevox/blob/aa8af90f13acf0dc20e49fb2a64b01333395281a/src/store/project.ts#L179

2021-09-08 17:48 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +              store.commit(SET_PROJECT_FILEPATH, { filePath: "" });
undefinedならハイフンがつかないかもしれません。
https://github.com/Hiroshiba/voicevox/blob/aa8af90f13acf0dc20e49fb2a64b01333395281a/src/store/project.ts#L18

2021-09-09 03:45 UTC, HyodaKazuaki commented on src/components/MenuBar.vue
> +              store.commit(SET_PROJECT_FILEPATH, { filePath: "" });
なるほど、その手がありましたね。
193279e で対応しました。

2021-09-09 03:51 UTC, HyodaKazuaki commented
> このままMenuBarに処理を書いても問題はないのですが、もしよかったらプロジェクトファイル系の処理が書いてある場所にまとめるというのはどうでしょう。
> `SAVE_PROJECT_FILE`辺りが参考になるかもしれません。
> https://github.com/Hiroshiba/voicevox/blob/aa8af90f13acf0dc20e49fb2a64b01333395281a/src/store/project.ts#L179-L183

分けたほうが理想的ですね。
4dcfc8e で処理をすべて`project.ts`にまとめたのですが、以下のダイアログはVueファイルに残しておいたほうがいいでしょうか？
https://github.com/Hiroshiba/voicevox/blob/4dcfc8e33fbb00288b8047a77b7d3bbcbc9aa8c0/src/store/project.ts#L34-L44

Reduxについてほとんど知らないのですが、Viewに関するものは`MenuBar.vue`に残しておいて、それ以降のプロジェクト関連の処理を`project.ts`に移す方がいいのかと思いました。
教えていただけると幸いです。

2021-09-09 04:46 UTC, Hiroshiba commented
見通しが立ちやすいので、ダイアログもVuex側に書いちゃって大丈夫です。

デファクトスタンダードな方法は僕も知らないですね・・・面白い課題感なのでどこかに転がってるかもです。
まあ、人間という非同期な外部APIにクエリを投げていると考えると、ダイアログ表示だけはVuexにあっても許される・・・かも？

2021-09-09 05:11 UTC, HyodaKazuaki commented
> 見通しが立ちやすいので、ダイアログもVuex側に書いちゃって大丈夫です。

すみません、Vuexについて全く知らないので教えていただきたいのですが、Vuex側は`vue`ファイルを指しているのでしょうか、それとも`ts`ファイルを指しているのでしょうか？

2021-09-09 05:46 UTC, Hiroshiba commented
あ！　こちらこそすみませんでした。　コードとしてはsrc/storeディレクトリ以下がvuexです。
https://github.com/Hiroshiba/voicevox/tree/2350215da5c55f46b6fddfb5ff6845e78cb7dc34/src/store

2021-09-09 07:35 UTC, HyodaKazuaki commented
> あ！　こちらこそすみませんでした。　コードとしてはsrc/storeディレクトリ以下がvuexです。
> https://github.com/Hiroshiba/voicevox/tree/2350215da5c55f46b6fddfb5ff6845e78cb7dc34/src/store

なるほど、ありがとうございます。
であれば、今の実装がVuex側にダイアログもまとめられているので、これで問題ないかと思います。

2021-09-12 07:45 UTC, Hiroshiba requested changes
すみません、レビューが遅れてしまいました。

2021-09-12 07:45 UTC, Hiroshiba commented on src/plugins/ipcMessageReceiverPlugin.ts
> +    window.electron.onReceivedIPCMsg(
ここはelectron→vuexのやりとりをしていて、`NEW_PROJECT`はvuex→vuexのやりとりなので、無くても大丈夫なはずです。

2021-09-12 07:57 UTC, HyodaKazuaki commented on src/plugins/ipcMessageReceiverPlugin.ts
> +    window.electron.onReceivedIPCMsg(
なるほど、わかりました。
01adb57 でrevertしました。

2021-09-12 16:07 UTC, HyodaKazuaki commented
https://github.com/Hiroshiba/voicevox/pull/202#discussion_r706778850 で指摘された点について、型も残っていたので`src/type/ipc.d.ts`についてもrevertを行いました。 23a3bbf

2021-09-12 16:11 UTC, Hiroshiba approved these changes
LGTM！　またのプルリクエストをお待ちしております！

（ちょっと文言だけ変えさせていただきます。）

2021-09-12 16:11 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +            label: "新規作成",
```suggestion
            label: "新規プロジェクト",
```

2021-09-12 16:12 UTC, merged