インストーラーを改良
Hiroshiba/voicevox pull request #231
Opened 2021-09-15 02:31 UTC by oov

## 内容

### 分割数や容量などを手動更新しなくてもいいようにしました

今までインストーラーのスクリプトに埋め込んでいた容量などの情報を自動で取得するようにしました。
動作の状態によって取得経路が異なります。

#### インストーラーと同じ場所に `voicevox-X.Y.Z-x64.nsis.7z` がある場合

- 7z ファイルのハッシュ値を調べ、一致する場合はオンラインアクセスは一切行いません
- すでに結合済みのファイルなので、ファイルの分割数の情報が必要になることはありません
- [LZMA SDK](https://sevenzip.osdn.jp/sdk.html) に付属するパブリックドメインプログラム `7zr.exe` をインストーラーに同梱しており、  
7z 展開後の総容量を展開せずに計算し、必要になる空き容量の計算に利用します  
- 何らかの理由で総容量の計算に失敗した場合も、その旨を伝えつつもインストール自体は強行可能です

#### それ以外の場合

- #230 で生成されるようになる  
`voicevox-X.Y.Z-x64.nsis.7z.ini` を最初にダウンロードし、分割数や総容量、ハッシュ値の情報を得ます
- これがマージされるまでは正しく動くインストーラーにはなりません

### インストール先を変更可能にしました

これに伴い以下のような変更を行いました。

#### ダウンロードするファイルの置き場所を変更

インストール先に `C:\Program files` などを選ぶ場合インストーラーに管理者権限が必要になるため、
セットアップの途中でインストーラーが起動し直すようになりました。

起動し直したインストーラーが再度ファイルのダウンロードを行わなくても済むように、
インストーラーの exe がある場所と同じ場所にファイルをダウンロードするようになりました。

なお管理者権限を持ってインストーラーが起動する際には既にダウンロードは完了している状態なので、
管理者権限を持った状態でオンラインアクセスを行うことは通常ありません。
（手動で管理者権限で起動した場合は別）

#### 空き容量の計算タイミングを変更

インストール先を選択するまでは調べるドライブが確定しないので、起動直後に空き容量チェックができなくなりました。
また、インストール先とインストーラーがあるドライブが一致するとも限らず、一度に簡潔に伝えるのが難しくなりました。

そこで、起動直後はダウンロードとファイルの結合に必要な空き容量だけを調べ、
インストール先の選択後はインストールに必要な空き容量だけを調べるように変更しました。
容量が不足している場合だけ画面に表示を出し、不足していても強行インストールも可能にしてあります。

また、空き容量が足りない場合でも一旦戻ってインストール先の変更などを行えるようにするため、
不足を伝えるダイアログをキャンセルしても強制終了しないようにしました。

### インストールの完了後、ダウンロードしたアーカイブを削除するか選べるようにしました

![image](https://user-images.githubusercontent.com/270909/133358944-c5da9f48-c47c-4950-8a4a-4cbd48637e43.png)

消し忘れたファイルを消すのは容易ですが逆は容易ではないためデフォルトではチェックなしにしてありますが、
基本的には不要なファイルであることがわかるように用済み感のある文言にしました。

## 関連 Issue

ref #210

2021-09-18 12:08 UTC, HyodaKazuaki requested changes
素晴らしい実装です。
特にマクロの差し込み方は大変勉強になりました。

いくつか気になる点やFIXMEになっていた点にコメントさせていただきました。
すでに考慮された上での実装かもしれませんが、確認をお願いします。

2021-09-18 12:08 UTC, HyodaKazuaki commented on build/installer.nsh
> +  readyPageLeave_finish:
これも以下の部分に相当する箇所だと思われます。
https://github.com/Hiroshiba/voicevox/blob/6116e49f80cba343471bb88ccd1ec1fdec15a24c/build/installer.nsh#L33

ここが「中断しますか？」としているのは、ユーザーが安易にOK系のボタンを押すことを懸念したためです。
ref. https://github.com/Hiroshiba/voicevox/pull/168#pullrequestreview-740664073

逆の設問になるような文面に変更したほうがいいかもしれません。

2021-09-18 16:49 UTC, Hiroshiba reviewed
良いですね！！　文言もインストーラー独特の言い回し感があって良いと思いました。

アップロードしないといけないファイルを確認しておきたいのですが、以前と同様にinsaller.exeと.7z.0系だけでしょうか？（.iniと`7zr.exe`も必要？）

2021-09-18 16:49 UTC, Hiroshiba commented on build/installer.nsh
> +${defineVariables}
見当違いかもしれませんが、この処理と`customInit`だと、`customInit`が先に実行されると思うのですが、`additionalProcess`の初期化がここなので、ちょっと違和感がありました。

2021-09-18 16:49 UTC, Hiroshiba commented on build/installer.nsh
> +  ${NSD_CreateLabel} 0 0 100% 12u "[インストール] を押すとコンピューターに $(^Name) ${VERSION} がセットアップされます。"
ユーザービリティ的に、ダウンロードにとても時間がかかってパソコンに付きっきりにできない場合もありそうなので、ダウンロードが終わったら勝手にインストールしてしまっても良いのかなと思いました。

2021-09-18 17:55 UTC, oov commented on build/installer.nsh
> +  ${EndIf}
一番大きな理由は、想定通りのファイルにきちんとアクセスできている状況下では
ファイルの破損が発生するのは「ファイルの後ろが欠けた」あたりが原因だと思うので、
その場合には高速に問題を検出できるからです。

大きなファイルに対してのハッシュ値計算はそれなりに時間がかかりますが、
そもそもサイズが異なる時点で確実に期待しているファイルではないことは明白なので、
ほぼオーバーヘッドがない方法で早くエラーを検出できるなら悪くないだろうということで入れています。

2021-09-18 18:15 UTC, oov commented on build/installer.nsh
> +    MessageBox MB_OKCANCEL|MB_DEFBUTTON2|MB_ICONEXCLAMATION "セットアップで一時的に必要な空き容量が不足しています。$\r$\n$\r$\n必要な容量: $0$\r$\n空き容量: $1$\r$\n$\r$\n本当に続行しますか？" IDOK welcomePageLeave_download
空き容量確認のダイアログは以前と若干役割が変わっており、
ここでキャンセルを押した場合の動作は「インストールを中断し、インストーラーを終了」ではなく、
「インストーラーのステップを進めずに今の画面に留まる」という挙動になっています。

以前はその後インストーラーを強制終了させていたので「中断」という表現が適切でしたが、
現状にはそぐわないため変更し、ボタンのデフォルトフォーカスをキャンセルにしています。

ここを逆の設問に変える場合、どのような表現が望ましいでしょうか？

2021-09-18 18:20 UTC, oov commented on build/funcs.nsh
> +    StrCpy $1 "バイト"
これはエンドユーザーが普段から見慣れていると思われる
Windows 標準アプリケーションであるエクスプローラーでのサイズ表記を参考にしています。
![image](https://user-images.githubusercontent.com/270909/133898584-77e5b9c3-196b-4dbf-b938-7ddaf1bd56e7.png)
![image](https://user-images.githubusercontent.com/270909/133898595-de16e4d5-608b-463f-aeb7-9a96d4f6e575.png)

2021-09-18 18:31 UTC, oov commented on build/installer.nsh
> +  readyPageLeave_finish:
以前と異なり今回はインストール先が変更可能になりました。

それに伴い
「空き容量が不足している」→「じゃあインストール先を変えよう」
という操作を望まれることが予想されるため、
「中断しますか？」でインストーラーを終了する流れを変更する必要がありました。

そこでこちらも以前のように中断ではなくキャンセルを押すと現在の画面に留まるように挙動を変更しており、
こちらも同じ理由により「中断」という表現がふさわしくなくなったと感じたため
デフォルトフォーカスをキャンセルにしたメッセージボックスに変更しています。

逆の設問に変える場合、どのような表現が望ましいでしょうか？

2021-09-18 19:56 UTC, oov commented on build/installer.nsh
> +  ;   "Download"    - ファイルのダウンロードとファイルの結合を行う
`"Download"` を `"DownloadAndConcatenate"` に変更しました。

2021-09-18 20:25 UTC, oov commented on build/installer.nsh
> +${defineVariables}
516 行目にあるこの `${defineVariables}` は変数の宣言のみで、初期化自体は `customInit` 内で行っています。
NSIS スクリプトでは C や Pascal などのように予め使う変数名を前方に宣言しておく必要があるようです。

ただ electron-builder の [installer.nsi](https://github.com/electron-userland/electron-builder/blob/1beda214d255211b36019e8d2febcd0868aae5f4/packages/app-builder-lib/templates/nsis/installer.nsi) を参照したところ `customHeader` を変数宣言に使えそうなので、`defineVariables` マクロを `customHeader` に改名し、この部分は削除してみたところ、エラーが出ました。

原因は `!insertmacro customHeader` は `!include "assistedInstaller.nsh"` より後ろにあり、`assistedInstaller.nsh` 内にある `!insertmacro customWelcomePage` が来るタイミングでまだ変数が定義できていない状態になってしまうからです。

よって、ここ以外に場所がなさそうに見えます。

2021-09-18 22:09 UTC, oov commented on build/installer.nsh
> +  ${NSD_CreateLabel} 0 0 100% 12u "[インストール] を押すとコンピューターに $(^Name) ${VERSION} がセットアップされます。"
それができるととても素晴らしいですね！

ダウンロードの時点ではインストール先が確定していないため、
現状ではダウンロード後の自動インストールはできません。

上記のインストール確認画面はインストール先の空き容量不足の際に
戻ってインストール先を変更できるようにするために仕方がなく挟んだクッションのようなものなのですが、
仮にこの画面がなかったとしてもダウンロード後にインストール先の選択画面が来るため、
このままでは自動インストールは不可能です。

もしインストール先を確定してからダウンロードを始めるような順序にした場合は、
「すべてのユーザー用にインストールする」を選んだ際に
権限を昇格した状態でファイルのダウンロードを始めることになります。

これによって、インストーラーと同じ場所に
ダウンロードしたファイルを作成した場合の挙動が変わるかもしれません。（未調査）
例えば昇格状態で `7z.0` だけをダウンロードしてインストーラーをキャンセルし、
昇格なしで続きをやろうとしてファイルの連結がきちんと動くのか？　などです。
（一応[昇格後にユーザー権限で処理はできる](https://nsis.sourceforge.io/mediawiki/index.php?title=UAC_plug-in&oldid=19055#Creating_a_user_shortcut)ようですが、こちらも詳しくは未検証）

その辺りの動作がすべて問題なく行えそうであれば
「ダウンロードが始まったあとは自動で最後まで」というのが可能かもしれません。

また、ファイルがダウンロード済みの場合には現在はインストーラーの起動直後にファイルの検証を行っています。
この待ち時間も後回しにすべきだと思いますので、インストール先の選択後が良さそうですね。

他にも変更によってどのような影響があるか、やってみないと見えてこない部分もあるかもしれません。

ただ、これらを実現するには現状のウィザードのフローを大幅に見直すことになります。
少なくとも `7z.ini` に展開後のファイルサイズも持たせ、
ダウンロード前にすべての空き容量警告を可能にする必要があります。
また、ダウンロード先の空き容量警告とインストール先の空き容量警告を一度の画面に出すことになると思うので、
画面の情報量が多く表示内容が煩雑になるのは避けられなさそうです。

ちなみに変更規模はとても大きいので時間はそれなりに掛かると思いますが、
この変更をやるならマージする前である、今の段階がいいと思います。
実現できるか試してみますか？

2021-09-18 22:22 UTC, oov commented
レビューありがとうございます。
返しやすいものから順次返信や修正などをしております。

> アップロードしないといけないファイルを確認しておきたい

今までのファイルに加えて `7z.ini` ファイルのアップロードが必要です。
インストーラーは最初に `7z.ini` ファイルをダウンロードして、ファイルの分割数などを確認します。
`7zr.exe` はインストーラーの exe に内包されるため別途アップロードする必要はありません。

2021-09-18 23:36 UTC, Hiroshiba commented on build/installer.nsh
> +    MessageBox MB_OKCANCEL|MB_DEFBUTTON2|MB_ICONEXCLAMATION "セットアップで一時的に必要な空き容量が不足しています。$\r$\n$\r$\n必要な容量: $0$\r$\n空き容量: $1$\r$\n$\r$\n本当に続行しますか？" IDOK welcomePageLeave_download
「停止しますか？」　→　はい／いいえ（キャンセルではなく）
とかでしょうか。もしくは「一時停止しますか？」「キャンセルしますか？」とかも良いかもです。

2021-09-18 23:43 UTC, Hiroshiba commented on build/installer.nsh
> +${defineVariables}
あれ、実行順序はcustomWelcomePage→customInitでしょうか。
であれば定義→初期化なので問題ないと思います！（逆だと思っていました）

2021-09-18 23:51 UTC, Hiroshiba commented on build/installer.nsh
> +  ${NSD_CreateLabel} 0 0 100% 12u "[インストール] を押すとコンピューターに $(^Name) ${VERSION} がセットアップされます。"
なるほどです。すごくよくわかりました。
たまにtempディレクトリを選んだ後、インストールディレクトリを選ぶものを見かけますが、このような理由なんですね。

であれば、頂いたプルリクエストの流れで良いように感じました。
ファイルを結合する関数などは変わらないと思うので、一旦マージしてからユーザーの声や使用感を確かめた後再検討しても良いかなと思いました。

2021-09-19 01:33 UTC, oov commented on build/installer.nsh
> +${defineVariables}
よく考えてみるとマクロを使わずに変数を直接宣言すればソースコード内での登場順を早めることができたので、
`customWelcomePage` 内の `${defineVariables}` を削除できました。
（プログラムの処理順などは全く一緒です）

これは `!insertmacro` が呼び出しや実行ではなく展開であることを把握しないと読み解きづらい問題だと思います。
`!macro` が C で言うところの `#define`、`!insertmacro` がその定義を実際に使う行為に近いです。

2021-09-19 02:21 UTC, oov commented on build/installer.nsh
> +    MessageBox MB_OKCANCEL|MB_DEFBUTTON2|MB_ICONEXCLAMATION "セットアップで一時的に必要な空き容量が不足しています。$\r$\n$\r$\n必要な容量: $0$\r$\n空き容量: $1$\r$\n$\r$\n本当に続行しますか？" IDOK welcomePageLeave_download
なるほど、「停止」や「一時停止」が選択肢に上がるのであれば、
近いニュアンスを持つ「中止」ボタンを含む `MB_ABORTRETRYIGNORE` も候補にあっても良さそうです。

![image](https://user-images.githubusercontent.com/270909/133913244-8921425f-4f9a-46fd-ba86-005d99b618ef.png)
[中止] で画面に留まる、[再試行] でもう一度空き容量チェック、[無視] で強行突破にできそうです。

2021-09-19 14:18 UTC, HyodaKazuaki commented on build/installer.nsh
> +  ${EndIf}
なるほど、確かにそうですね。
`FileSeek`の方が処理にかかる時間も短く済みそうなので良さそうです。

2021-09-19 14:28 UTC, Hiroshiba commented on build/installer.nsh
> +    MessageBox MB_OKCANCEL|MB_DEFBUTTON2|MB_ICONEXCLAMATION "セットアップで一時的に必要な空き容量が不足しています。$\r$\n$\r$\n必要な容量: $0$\r$\n空き容量: $1$\r$\n$\r$\n本当に続行しますか？" IDOK welcomePageLeave_download
再試行、良いですね！！

３ボタンにするなら、それぞれの主語・目的語が何なのかわかるようにできると嬉しそうです。
現状だと、何を再試行するのか（空き容量の検出かセットアップ）、何を中止するのか（セットアップかこの工程か）、無視すると何が起きるのかが伝わりづらいかもしれません。

だいぶ考えてみましたが、「空き容量を検出できませんでした」にすると再試行の対象が「検出」だと伝わりやすいかもです。
また「中止」は「戻る」か「キャンセル」でどうでしょう。
「無視」は消去法で続行のことだとわかりそうなので良さそうに感じました。

2021-09-19 14:28 UTC, HyodaKazuaki commented on build/installer.nsh
> +  readyPageLeave_finish:
> そこでこちらも以前のように中断ではなくキャンセルを押すと現在の画面に留まるように挙動を変更しており、
「中断」という表現がふさわしくなくなったと感じたため

確かに、中断だとインストーラが終了してしまいそうなイメージですね。
では、「本当に続行しますか？」の代わりに「インストール先を他のドライブに変更しますか？」に変更するのはいかがでしょうか。

```nsh
MessageBox MB_YESNO|MB_ICONEXCLAMATION "インストールに必要な空き容量が不足しています。$\r$\n$\r$\n必要な容量: $0$\r$\n空き容量: $1$\r$\n$\r$\nインストール先を他のドライブに変更しますか？" IDNO readyPageLeave_finish
```

2021-09-19 21:12 UTC, oov commented on build/installer.nsh
> +    MessageBox MB_OKCANCEL|MB_DEFBUTTON2|MB_ICONEXCLAMATION "セットアップで一時的に必要な空き容量が不足しています。$\r$\n$\r$\n必要な容量: $0$\r$\n空き容量: $1$\r$\n$\r$\n本当に続行しますか？" IDOK welcomePageLeave_download
「空き容量を検出できませんでした」だと少し問題があると感じます。
「現在の空き容量を調べ、不足していることが判明した」ということではなくて、
単純に「空き容量の調査に失敗した」と伝えているように感じました。

そうなると「再試行を連打すればそのうち成功する？」とか、
別の可能性を感じさせてしまうようにも思いました。

----

![image](https://user-images.githubusercontent.com/270909/133941855-66463554-7ed3-4274-a6b8-c826636714a5.png)
Windows 標準のエクスプローラーにおいては空き容量が不足しているドライブへファイルをコピーしようとした際には
「ファイルをコピーするには容量が必要です」と伝えることで、
再試行の対象がファイルのコピーであることを明確にしているようです。

----

![image](https://user-images.githubusercontent.com/270909/133942818-64eb35c9-f81f-47d9-aee3-207a6be61fc6.png)

これを踏まえ、`中止` や `再試行` をする対象が「ファイルのダウンロード」、
`無視` する対象が「空き容量の不足」であることを明確にしてみました。
合わせて、どのドライブの容量を確保すればいいのか不明瞭だったのでドライブ名も加えてみました。
いかがでしょうか？

2021-09-19 21:32 UTC, Hiroshiba commented on build/installer.nsh
> +    MessageBox MB_OKCANCEL|MB_DEFBUTTON2|MB_ICONEXCLAMATION "セットアップで一時的に必要な空き容量が不足しています。$\r$\n$\r$\n必要な容量: $0$\r$\n空き容量: $1$\r$\n$\r$\n本当に続行しますか？" IDOK welcomePageLeave_download
なるほど、良いと思います！！

2021-09-19 22:32 UTC, oov commented on build/installer.nsh
> +  readyPageLeave_finish:
「インストール先を他のドライブに変更しますか？」に「はい」を答えた場合に期待される動作は
「インストール先の入力画面の表示」になりますが、実際には以下の画面に留まるだけなので、
この状況下においては他の方向性を模索したほうがいいように感じました。

![image](https://user-images.githubusercontent.com/270909/133944818-63c1aa55-b939-4c18-9cb2-1277655dc1be.png)
留まる画面の表示例です。

現状の [MUI2](https://nsis.sourceforge.io/Docs/Modern%20UI%202/Readme.html) では[インストール先の入力画面にフックを組み込んでもインストール先のパスを取得できない](https://github.com/electron-userland/electron-builder/blob/1beda214d255211b36019e8d2febcd0868aae5f4/packages/app-builder-lib/templates/nsis/assistedInstaller.nsh#L28-L29)ようなので、
インストール先の入力画面には問い合わせて留まるような処理を書くこと自体ができません。

----

もう一方での議論を踏まえて、`MB_ABORTRETRYIGNORE` を使ったメッセージを考えてみました。

![image](https://user-images.githubusercontent.com/270909/133944275-87e420ff-ed32-486c-90e0-17f6182f9313.png)

いかがでしょうか？

2021-09-19 23:30 UTC, oov commented on build/installer.nsh
> +    StrCpy $0 "OK"
その認識でおそらく合っていますが、コメントでは伝わりづらいかも知れませんので、
インストーラーですべてのユーザー用にインストールするを選んだ場合の流れを大体の所要時間と共にまとめました。

ダウンロードの所要時間は現状のインストーラーを元にし、その他は私の環境での大体の実測値です。

1. 一般ユーザー権限でインストーラーを起動
2. 7z.ini をダウンロード(恐らく1秒程度、未検証)
3. ようこその画面と共にダウンロード容量を表示、ユーザーは [次へ] を押す
4. 7z.0 をダウンロード(約51秒)
5. 7z.0 のハッシュ値検証(約4秒)
6. 7z.1 をダウンロード(約51秒)
7. 7z.1 のハッシュ値検証(約4秒)
8. 7z.2 をダウンロード(約33秒)
9. 7z.2 のハッシュ値検証(約3秒)
10. ファイル結合(約37秒)
11. 7z のハッシュ値検証(約30秒)
12. ユーザーは「すべてのユーザー用にインストールする」を選んで [次へ] を押す
13. ここで昇格、UACのダイアログが表示されて別のインストーラーが起動し、以降を引き継ぐ
14. 7z のハッシュ値検証(約30秒) ← **これを省くための処理**
15. ユーザーはインストール先フォルダーを選択して [次へ] を押す
16. インストール容量の計算(1秒未満)
17. [インストール] を押す
18. インストール(約80秒、この途中で約30秒のハッシュ値検証がもう一度行われている)
19. インストール完了の画面

14 での待ち時間は結構タイミングが悪く、
本来はまとまっているはずの「ユーザーがインストーラーを操作可能なシーン」を
分散させてしまう直接的な原因になっています。

これがなければファイルのダウンロード後にインストールを始めるまでの間で待ち時間はほぼゼロであり、
しかもこの処理は 11 のステップを繰り返しているだけの無意味な処理でもあるため、
明らかに省くことに大きなメリットがあると考えた上で行っている処理です。
（そもそも 11 のステップで失敗した場合はインストーラーは強制終了します）

必ず検証したとしても無意味な待ち時間が増える以外の変化はないため
外したほうがいい明確な理由があれば外しても構わないと思います。

しかし「ここの判定ロジックが将来的にバグになる可能性」について私にはイメージができておらず、
進むべき方向性について正しくビジョンが共有できていないと感じました。
もう少し具体的な説明や、詳しい根拠をご説明いただけると嬉しいです。

2021-09-20 03:29 UTC, oov commented on build/installer.nsh
> +    ; FIXME: 一部のファイルがダウンロード済みの場合は表示が正しくない。気にしすぎ？
現在の `allPartedFilesExists` は異常が見つかった場合はそこで打ち切る構造になっているため、
今のままだと `7z.0` がなく `7z.1` があるような場合に上手く行かなくなりそうです。

そこで、打ち切らずにすべてのファイルを調べ、
ついでにダウンロードすべきファイルの容量を計算するようにし、
名前を `allPartedFilesExists` から `calcDownloadSize` に変更しました。

2021-09-20 03:31 UTC, oov commented on build/installer.nsh
> +  ${EndIf}
`allPartedFilesExists` は破損ファイルが見つかった時点で打ち切るため、ここでの検証は必要な処理でした。
しかし `calcDownloadSize` に変更した影響ですべてのファイルをきちんと検証するようになったので、
こちらではファイルが見つかった時点で "OK" を返すように変更しました。

2021-09-20 03:53 UTC, oov commented
レビューにて上がっていた点のうち、
方向性が定まっているものに関してはすべて修正しました。

エッジケースでしか発生しない一部の問題は `FIXME` で今後の課題として元々は残すつもりでしたが、
レビューしていただいたのでそれらに関しても合わせて修正しました。

2021-09-20 05:03 UTC, HyodaKazuaki approved these changes
LGTMです。
返信いただいたコメントの箇所もすべて確認しました。

2021-09-20 07:30 UTC, oov commented
大きなプルリクエストだったにも関わらず丁寧にレビューしていただきまして、本当にありがとうございました。
自分では気付けない部分を数多く修正することができ大変助かりました。

2021-09-20 08:01 UTC, Hiroshiba commented on build/installer.nsh
> +    StrCpy $0 "OK"
なるほど！ハッシュ値計算は時間がかかるんですね！！即座に終わるものだと思っていました。

バグは例えば、別経路に気づかずに`verifyArchive`内で副作用のある処理（変数への代入とか）が将来実装された場合です。
が、30秒変わるのは大きいと思うので、迂回路はあっても良さそうに感じました。

2021-09-20 10:06 UTC, oov commented on build/installer.nsh
> +    StrCpy $0 "OK"
なるほど、懸念のニュアンスが少しわかりました。

おそらく考えられている懸念の本質としては、
「別プロセスを起動してこれまでの処理を引き継ぐ」という
極めてトリッキーな処理を要求される UAC の存在そのものではないかと思っております。
これが原因で通るコードパスが大きく変化すると思いますし、バグに温床にもなると思います。

実は `${UAC_IsInnerInstance}` に頼らずに同じことを実現するアプローチは一応もうひとつあります。
それは、`verifyArchive` にプロセスを跨いで[メモ化](https://ja.wikipedia.org/wiki/%E3%83%A1%E3%83%A2%E5%8C%96)できるような仕組みを導入することです。

これができれば、複数回 `verifyArchive` が呼ばれたとしても2回目以降をほぼオーバーヘッドなしにできます。
複数回の呼び出しでほぼオーバーヘッドがなくなるのであれば、
使うシーンでわざと `verifyArchive` を複数回呼ぶことでメモ化の処理が壊れてないか強制的に検証もできると思います。
そうすれば通るコードパスを安定させられるので、懸念をほぼ解消できるのではないかと思います。

ただ、これを実現しようと思うと、
例えば `.7z` の検証に成功した場合は `$TEMP` フォルダー に `.7z.verified` のようなファイルを作成しておき、
もしそのファイルがあるなら検証済みとして扱う、みたいな手法しか今のところ浮かびません。
この `.7z.verified` は削除し忘れると `.7z` の内容が変わったあとも検証済みとして扱ってしまう危険性がありますし、
`$PLUGINSDIR` のように NSIS が自動で削除してくれる場所でもないので、`${UAC_IsInnerInstance}` 以上に茨の道です。
（`$PLUGINSDIR` はプロセスごとに固有のフォルダーが割り当てられるのでおそらく利用できないと思います）

そういう現状を踏まえての `${UAC_IsInnerInstance}` を利用した分岐なので、
今後の課題ということで注意深く扱い、レビューの際に念入りにチェックする、
という方向でひとまずお茶を濁していただけると嬉しいです。

2021-09-20 10:24 UTC, Hiroshiba commented on build/installer.nsh
> +    StrCpy $0 "OK"
なるほど、メモ化は思いつきませんでした。
ファイル書き出しする手はありですが、たしかにややこしくなりそうなので、一旦置いておくのが良さそうに感じました！

将来ファイルサイズが小さくなってverifyに時間がかからなくなったり、証明書を取得して最初からrootで実行できるようになったら、機会見て分岐減らすことを検討する感じで・・・！

2021-09-20 10:28 UTC, Hiroshiba approved these changes
LGTM！　お疲れさまでした！
（ @HyodaKazuaki さんもありがとうございました！）

2021-09-20 10:28 UTC, merged