非同期コマンドの新方式への移行例
Hiroshiba/voicevox pull request #267
Opened 2021-09-25 18:13 UTC by Segu-g

## 内容

非同期な旧コマンドを新コマンドに移行する例としてアクセント周りに関連する以下のコマンドを移行しました。
| 移行前 | 移行後|
| --- | --- |
| `CHANGE_ACCENT` | `COMMAND_CHANGE_ACCENT`|
| `CHANGE_ACCENT_PHRASE_SPLIT` `TOGGLE_ACCENT_PHRASE_SPLIT` | `COMMAND_CHANGE_ACCENT_PHRASE_SPLIT` |

ref #258
ref #233

## 関連 Issue

ref #116

## スクリーンショット・動画など

## その他

2021-09-25 20:08 UTC, Hiroshiba requested changes

2021-09-25 20:08 UTC, Hiroshiba commented on src/store/audio.ts
> -      return dispatch(FETCH_AND_SET_MORA_DATA, {
`FETCH_AND_SET_MORA_DATA`が２回展開され、AccentPhrasesをコピーして`changeIndexes`引数の部分だけ代入する処理が３箇所にありそうです。
この処理を`FETCH_MORA_DATA`に移動すればコードが綺麗になりそうな気がしました。

2021-09-25 20:22 UTC, Segu-g commented on src/store/audio.ts
> -      return dispatch(FETCH_AND_SET_MORA_DATA, {
処理を切り分けて共有するのは賛成ですが`FETCH_MORA_DATA`に移動するのは反対です。ユーティリティ関数として書くのが良いと思うのですが`FETCH_MORA_DATA`に移すべき理由は何ですか？

2021-09-25 20:29 UTC, Segu-g commented on src/store/audio.ts
> +        {
ブロックにすることでtoggle処理の纏まりである事を明示し、ローカル関数等を定義するスコープを作成する目的です。
冗長だと思われたなら👎してもらえれば削除します。

2021-09-25 20:41 UTC, Segu-g commented on src/store/audio.ts
> +export { SET_ACCENT_PHRASES };
audio.ts内の旧コマンド部分に`SET_ACCENT_PHRASES`をActionとして読んでいる部分があったので,その部分を壊さないようにActionを定義しました。外部からの呼び出しはありませんがActionとして存在する事を示す為に`export`していました。

2021-09-25 20:51 UTC, Hiroshiba commented on src/store/audio.ts
> -      return dispatch(FETCH_AND_SET_MORA_DATA, {
あ、処理を切り分けて共有するのが主目的です！

2021-09-25 21:00 UTC, Hiroshiba commented on src/store/audio.ts
> +        {
なるほどです。消し忘れでなければlocal変数を分けたいからかな、と思っていました。
結構一般的に行われることなのであれば、あっても良いと思います。

2021-09-25 21:03 UTC, Hiroshiba commented on src/store/audio.ts
> +export { SET_ACCENT_PHRASES };
なるほどです。
そのことがわかるようにコメントを残すか、たぶん困ることはないのでexportしないようにすると良さそうに感じました。

2021-09-26 11:10 UTC, Segu-g commented on src/store/audio.ts
> -      return dispatch(FETCH_AND_SET_MORA_DATA, {
`copyAccentPhrasesPart`関数をhttps://github.com/Hiroshiba/voicevox/pull/267/commits/8d892c12a5f16b732f296e4e28914db9b0b39b18 で定義してみましたがどうでしょうか

2021-09-26 19:25 UTC, Hiroshiba commented on src/store/audio.ts
> -      return dispatch(FETCH_AND_SET_MORA_DATA, {
プルリクエストでは、２箇所の`dispatch FETCH_AND_SET_MORA_DATA`が展開され、↓の`dispatch SET_ACCENT_PHRASES`以外のコードがコピーされています。
https://github.com/Hiroshiba/voicevox/blob/9aaa9bb513fd09103b67c0f43ff912b6cc48beb8/src/store/audio.ts#L535-L558
結構複雑なこのコードが３箇所似コピーされているので、その部分を関数かアクションに切り出すと良さそうかもと感じた次第です！

2021-09-26 20:12 UTC, Segu-g commented on src/store/audio.ts
> -      return dispatch(FETCH_AND_SET_MORA_DATA, {
https://github.com/Hiroshiba/voicevox/pull/267/commits/273b0ad8ea75e061374a173e7a09c903d30c621b で`FETCH_AND_COPY_MORA_DATA`アクションを定義し、`FETCH_AND_SET_MORA_DATA`相当の処理を書きました。

2021-09-27 13:07 UTC, Hiroshiba approved these changes
LGTM！！

2021-09-27 13:07 UTC, merged

2021-09-27 14:12 UTC, Segu-g commented on src/store/audio.ts
> +      if (query === undefined) throw Error("");
マージされた後に気づいたのですがここのエラーメッセージを書き忘れていました😥

2021-09-27 14:39 UTC, Hiroshiba commented on src/store/audio.ts
> +      if (query === undefined) throw Error("");
ここに来ることはなさそうだったので、このままでも大丈夫な気はします。
もしよかったら別プルリクエストのタイミングで足して頂ければ・・・！