[WIP]Getters、Actions、Mutationsの型を抽出する
Hiroshiba/voicevox pull request #269
Opened 2021-09-26 14:29 UTC by y-chan

## 内容

#268 で厳密な型付けをするにあたって必要な型情報を抽出しました。
現状、コード内ではどこからも使われていません。

## 関連 Issue

#268 の前提PR

2021-09-26 17:06 UTC, y-chan commented on src/store/audio.ts
> +export type AudioCommandGetters = Record<string, never>;
メモ: 以下でないとうまくいかない可能性があるので、置き換えることになるかもしれない...
```suggestion
// eslint-disable-next-line @typescript-eslint/ban-types
export type AudioCommandGetters = {};
```

2021-09-27 05:18 UTC, y-chan commented
とりあえず、すべてのGetters、Mutations、Actionsの型情報を抽出しました。
その他に書いた通り、先に他のPRがマージされるのであれば、書き換える必要があります。

2021-09-27 09:09 UTC, Hiroshiba commented
良いですね！！

audio.tsに型を書いてそれをtype.tsにインポートしていますが、逆（type.tsに型書いてaudio.tsにインポート）の方が良いかもと思いました。

2021-09-27 15:19 UTC, y-chan commented
一部の型情報が欠落していたので、それの補完と一緒に移動させますね

audioのものを移動させるなら、他のものもすべてtype.tsに移動すべきですね...

2021-09-27 17:06 UTC, Hiroshiba requested changes
レビュー可能になったらコメントorレビューリクエストを頂けると！

2021-09-27 17:10 UTC, y-chan commented
すべての型をtypesに移動させました。
#271 がマージされたので、それをもとにrebaseしてレビューリクエスト投げます。

2021-09-27 17:28 UTC, y-chan commented on src/store/command.ts
> +export class OldCommand<S> {
https://github.com/Hiroshiba/voicevox/pull/233/files#diff-ff89d60b349d9c073614fd7ea588e2e80ba7cc9b6f182433e08b78305660bed0L19-R29

typesにすべてのGetters、Actions、Mutationsを集約するために、上記のPRでexportを消したのを戻しています。
おそらく元の`export`を消したのは、使われることを防ぐためだと思うのですが、いったんは仕方ないということで...

2021-09-27 17:37 UTC, Hiroshiba approved these changes
LGTM！

プルリクエストを頂いて気づいたんですが、command→typeの参照があったんですね。
type→commandも必要なので循環参照になりそうですね・・・。

2021-09-27 17:37 UTC, merged