Linux用実行バイナリ（AppImage）の自動ビルド (#218)
Hiroshiba/voicevox pull request #270
Opened 2021-09-26 16:00 UTC by aoirint

## 内容

Linux用実行バイナリの自動ビルドを追加します。

#264 のWorkflow部分に追記しているため、 #264 の差分を含んでいます。

## 関連 Issue

close #218

2021-09-26 19:28 UTC, buckw6eat commented
単純にはシンボリックリンクを貼ると動くかと思います。

```bash
ln -s libnvrtc-builtins-07fb3db5.so.11.1 libnvrtc-builtins.so.11.1
```

LibTorch には 4 つほど CUDA Toolkit 由来 ( /usr/local/cuda-11/lib64 ) のファイルが同梱されているようです。これらは本来 ldconfig が実行されるとシンボリックリンクができるはずですが、ubuntu 18.04 ビルドで ldconfig が機能しないとか、単に artifact で出すとリンクではなく実体がコピーされるとか、Windows とリリースまでのワークフローが共通化しにくいかも。

- libcudart-6d56b25a.so.11.0 (libcudart.so.11.0)
- libnvToolsExt-24de1d56.so.1 (libnvToolsExt.so.1)
- libnvrtc-3a20f2b6.so.11.1 (libnvrtc-builtins.so.11.1)
- libnvrtc-builtins-07fb3db5.so.11.1 (libnvrtc-builtins.so.11.1)

2021-09-27 00:57 UTC, aoirint commented
@buckw6eat 

> シンボリックリンクを貼ると動く
> ...
> 必要なのは上記だけのようです

なるほど、ありがとうございます！

本来の名前 (soname)をもった.soについては、Dockerイメージビルド時に、
ldconfigの代わりに、自前でシンボリックリンクを作成する形がいいのかなと思いました。

LibTorchに同梱されていないCUDAの共有ライブラリについては、
ENGINEの実行バイナリビルドの方で、
Windowsの方では必要なさそうだったので別途同梱しないようにしていたのですが、
Linuxでは同梱するようにしていました。
この同梱が必要なさそうですね。
自動ビルドしたENGINEに同梱している共有ライブラリは、不要なものがあったり、2重に含まれているものがあるように思いました。

GPU版Dockerイメージのベースイメージをnvidia/cudaにする必要もないかもしれないです。

> 単に artifact でアップロードするとリンクではなく実体がコピーされる

ENGINEの実行バイナリビルドの方で、一度tarに固めてからartifactとしてアップロードするようにすれば、
シンボリックリンクを保持できるのかなと思いました。

ベースイメージにnvidia/cudaを使うのをやめられれば、tarに固めるためのCIの容量に余裕ができるかもです。
あとは、使用済みのDockerイメージを削除して、単一のJob内で容量を確保できるかもです。

2021-09-27 11:43 UTC, buckw6eat commented
> LibTorchに同梱されていないCUDAの共有ライブラリについては、
> ...
> Linuxでは同梱するようにしていました。
> この同梱が必要なさそうですね。

見落としが無ければ、Linux の ENGINE 実行バイナリも明示的には LibTorch からのものだけのように思います。
補足しますと、リンク貼り (soname そのままのファイル名) が必要なのは `libnvrtc-builtins.so.11.1` のみであった、と言いたかったのです。１つだけですから、リンクでなくコピー (あるいはリネーム) で対応してもよいかもしれません。

GPU 版用の Docker イメージのベースが nvidia/cuda でなくてもよいかも、は同意です。

2021-09-29 23:39 UTC, aoirint commented
#282 がマージされれば問題は解決するので、readyにします。

2021-10-02 07:14 UTC, Hiroshiba commented
インストールの案内をどうしようか迷っています。
windows版は[webサイト](https://voicevox.hiroshiba.jp/)のダウンロードボタンを押したあとに「インストール版」をクリックすることでインストーラー.exeが振ってきます。
同じようにスクリプトが振ってくる形にするか、別の形にするかなどを考えています。

2021-10-02 12:58 UTC, aoirint commented
```bash
VERSION=X.X.X curl -fsSL https://raw.githubusercontent.com/Hiroshiba/voicevox/main/installer_linux.sh | bash

VERSION=X.X.X curl -fsSL https://raw.githubusercontent.com/Hiroshiba/voicevox/X.X.X/installer_linux.sh | bash
```

上のようなコマンドと、実行内容を見てから実行したい人向けのインストールスクリプトのダウンロードリンク、をおいておく形を考えていました。コマンドを使わないユーザの視点がほしいです...。

Ubuntu 20.04で、ブラウザでダウンロードしたシェルスクリプトを実行するには、GUI上だけでは完結しない気がしました。
`chmod +x`はGUI操作で代替できますが、実行にはターミナルを開く必要があるように思いました。

```bash
bash installer.sh
# Or
chmod +x installer_linux.sh
./installer.sh
```


調査

<details>

シェルスクリプトを使ったAppImageのインストーラという形式は、文書系ソフトウェアのJoplinを参考にしています。こちらはAppImageのダウンロードリンクと、インストーラ・アップデータ機能のあるシェルスクリプトの実行コマンドがおかれています。

- https://joplinapp.org/help/#desktop-applications

画像処理ソフトウェアのGIMPは、バイナリをflatpakというパッケージマネージャ向けに配布していて、flatpakrefというインストール情報が記述されたテキストファイルのダウンロードリンクをおいています。
しかし、Ubuntu 20.04の標準GUIパッケージ管理ソフト（GNOME Software Center）では、`Failed to install file: not supported`のように表示され、実行できませんでした（コマンドからインストールする必要がある）。
また、flatpakは別途インストールされていることが前提になっています（Ubuntu 20.04時点ではデフォルトで入っていません）。

- https://www.gimp.org/downloads/
    - 原因: https://askubuntu.com/a/1244275

![gimp](https://user-images.githubusercontent.com/27213639/135715606-da010dd2-f60a-4e70-8448-93d3f6718724.png)

GUIで完結させるには、Ubuntuに関してはdebかtar.gzを使う方法がとられているのかなと思いました。
debの場合、deb内部に必要なファイルが同梱されているか、パッケージを配布するサーバ（リポジトリ）が用意されている（CUDA deb (network)）ように思いました。
Discordは、tar.gz形式でElectronのビルド成果物（linux-unpacked = linux-nvidia-prepackage/linux-cpu-prepackage）を合わせて配布していました。
CUDAのrunfileは、Makeselfというプログラムで作られたオフラインインストーラのようでした（コマンドで実行）。

- Slack (deb/rpm): https://slack.com/intl/ja-jp/downloads/linux
- Discord (deb/tar.gz): https://discord.com/
- Microsoft Teams (deb/rpm): https://www.microsoft.com/ja-jp/microsoft-teams/download-app#desktopAppDownloadregion
- Atom (deb/rpm): https://atom.io/
    - https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux
- CUDA (deb/runfile): https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network

![slack](https://user-images.githubusercontent.com/27213639/135715967-45ffb4d9-5e65-469c-8b76-c9433478a3f5.png)

- OBS Studio (aptコマンド): https://obsproject.com/ja/download

</details>

Discordは、Electronのビルド成果物を、debに加えてtar.gz形式でも配布していました。

VOICEVOXでも、Windows用のzip版に相当する形で、DiscordのようにLinux用のtar.gz版を用意してもよさそうに思いました。
tarは実行権限を保持するため、`chmod +x`の操作をする必要もありません。

配布物は、linux-nvidia-prepackage/linux-cpu-prepackageでよさそうですが、
現在のWorkflowではzipでArtifactにアップロードするため、VOICEVOXとENGINEに実行権限が付与されません。
tar.gz版用に、tarに固めてからArtifactにアップロードするStepを追加してもよさそうに思いました（おそらくtar.gzがzipの中に入ることになりますが）。

2021-10-02 16:26 UTC, aoirint commented
- tar.gzのArtifact追加
- size, hashの計算・listへの出力

を追加で実装しました

2021-10-03 09:40 UTC, Hiroshiba commented
> tar.gzから展開した voicevox をダブルクリックで実行することはできなかった

あ、ライブラリが見つからないためですよね・・・。
この問題も`--set-rpath`で解決したりするのでしょうか。
ぱっと検索してみた感じ、実行バイナリも変更できそうかもです。
https://stackoverflow.com/questions/13769141/can-i-change-rpath-in-an-already-compiled-binary

2021-10-03 09:41 UTC, Hiroshiba requested changes
コメント追加のお願いの点だけがRequest changesで、それ以外はコメントレベルです。

2021-10-03 09:41 UTC, Hiroshiba commented on .github/workflows/build.yml
> +      #   - run
ちょっとだけ気になったのですが、このコメントは１つ下用のコメントだったりしますか・・・？

2021-10-03 09:41 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          chmod +x prepackage/run
思いつきですが、ここ以降の処理は全てlinux用なので、別のジョブに分けてしまっても良いかもと思いました。
（処理の数がそこまで多くないので、今のままでも全く問題ないと思います！）

2021-10-03 09:41 UTC, Hiroshiba commented on .github/workflows/build.yml
> +      - name: Create Linux tar.gz
なぜzipではなくtar.gzにする必要があるのかはピンとこない場合もありそうなので、コメントでメモ書きをお願いしたいです。

2021-10-03 09:41 UTC, Hiroshiba commented on .github/workflows/build.yml
> +      - name: Split AppImage artifact
ここの処理は`splitNsisArchive.js`とよく似ているので共通化できるかもと感じました。
行数的にはコマンドで実行したほうが圧倒的に短そうですね。
ただ、nsisとappimageで前処理が若干異なっているのもあって（.iniか.tsvか）、今の形でも良いかなと思いました。

2021-10-03 11:01 UTC, aoirint commented on .github/workflows/build.yml
> +      #   - run
`Set BUILD_IDENTIFIER env var` 以降をひとかたまりの処理と見て、その全体のコメントのつもりでした。
説明の追記に合わせて移動しました！

2021-10-03 11:01 UTC, aoirint commented on .github/workflows/build.yml
> +      - name: Create Linux tar.gz
追記しました！

2021-10-03 11:24 UTC, aoirint commented on .github/workflows/build.yml
> +      - name: Split AppImage artifact
同意です。

ただ、nsisの方ではインストーラが生成された時点ですでに7z圧縮されているので、
分割には別コマンドを使う必要がありそうです。
AppImageの方も統一はできますが、効率的でないと思いました。

```shell
# 2桁の1から始まる連番で分割
split --suffix-length=2 --numeric-suffixes=1 --bytes 1G {filename}.7z {filename}.7z.
```

7zファイルを作ってから `split` で分割しても、`7z -v1g` のように圧縮しながら分割保存しても、
バイナリとしては同じ操作をしているように思いました。

2021-10-03 11:44 UTC, aoirint commented on .github/workflows/build.yml
> +          chmod +x prepackage/run
分けてもいいと思います。

ジョブを分けていないのは、以下のような理由ですが、それほど強い理由ではないです。

- Windowsのzip版 `windows-{cpu,nvidia}-prepackage` と同じジョブでtar.gz版のアップロードを完了する
    - 処理上区別はなさそうなので、実質的に意味はない
- `artifact_name` を列挙する回数を減らす

ほかに、`build-distributable` でもアップロードするジョブを揃えていますが、Windowsでは、ジョブ中でなにもしていないのが気になっています。

それぞれの成果物が完成したら、すぐにAssetやArtifactにアップロードするようにする方法もあると思いました。

2021-10-03 15:08 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          chmod +x prepackage/run
こちらとしても強い重いはなかったのと、理由も全然納得できるので、現状のままでも良いと思いました。
（どちらかというとActionsにstepをまとめるstep blockみたいなのがほしいですね・・・。）

2021-10-03 15:11 UTC, Hiroshiba approved these changes
LGTM！　また１回チェックでビルドを回してみたいと思います！

2021-10-03 15:11 UTC, merged