`FETCH_AND_SET_SINGLE_ACCENT_PHRASE`の新方式への移行
Hiroshiba/voicevox pull request #274
Opened 2021-09-28 17:41 UTC by Segu-g

## 内容

`FETCH_AND_SET_SINGLE_ACCENT_PHRASE`をoldCommandを利用しない`COMMAND_CHANGE_SINGLE_ACCENT_PHRASE`に変更しました。

ref #258
ref #233

## 関連 Issue

ref #116

## スクリーンショット・動画など

## その他

2021-09-28 18:49 UTC, Hiroshiba requested changes
メンテナをしていて気づいたのですが、メソッドの移動とロジックの変更が同時に行われるとレビューにかなりの時間がかかります。
移動と名称変更くらいならすぐわかるのですが（`git diff --colord-moved`が便利）、次回からはロジックが変わるレベルのリファクタリングは別プルリクエストにして頂けるととても助かります🙇

（今回だと、例えば`SET_SINGLE_ACCENT_PHRASE`から`popUntilPause`引数をなくし、処理を`CHANGE_SINGLE_ACCENT_PHRASE`に移すとか）

2021-09-28 18:49 UTC, Hiroshiba commented on src/store/audio.ts
> +    [SET_AUDIO_MORA_DATA]: (
重複していそうです。
（意外かもですが、このことに気づくのに結構時間がかかりました。）

2021-09-29 03:06 UTC, Segu-g commented on src/store/audio.ts
> +    [SET_AUDIO_MORA_DATA]: (
差分をチェックしているときに見逃していました...
修正しました！

2021-09-29 03:18 UTC, Segu-g commented
確かにこのプルリクエストに含める必要性がない変更でしたね・・・
次から気を付けます。

2021-09-29 04:22 UTC, Hiroshiba approved these changes
LGTM！

2021-09-29 04:22 UTC, merged