`PUT_TEXTS`のコマンドへの移行
Hiroshiba/voicevox pull request #296
Opened 2021-10-03 14:21 UTC by Segu-g

## 内容

`audioStore`上にあった`PUT_TEXTS`アクションをコマンド化し`COMMAND_PUT_TEXTS`として実装し直しました。
これによってペースト処理がUNDO/REDOのHistoryに記録されるようになります。

また、#284 でqinputにdebounceが付いたことにより、Storeの値が古くなることがあったためセルが空文字列("")の時にそのセルを上書きする処理を無効化しました。
追加したコマンドはActionが追加した`audioKey`の配列を返すのでペーストした最後の要素にセルを追加するようにしました。

ref #258
ref #233

## 関連 Issue

ref #116

## スクリーンショット・動画など

## その他

2021-10-03 14:41 UTC, Segu-g commented on src/store/audio.ts
> +      }
`INSERT_AUDIO_ITEM`は`indexof(prevAudioKey)`の計算量が必要なので`prevAudioKey`の後に直列に挿入するだけでいいロジックではそれぞれ挿入していくのは無駄です。(n (c + n / 2)回の比較となり O(n^2)掛かる)
`INSERT_AUDIO_ITEM`を複数個に対応させるのが道理だと思いますが、実装の複雑度が上がることを考えると、本当に実装すべきか分かりませんでした。
ここはどのくらいのオーダーのtextsが来ると想定すればいいでしょうか？

2021-10-03 15:57 UTC, Hiroshiba requested changes
良いですね！！

2021-10-03 15:57 UTC, Hiroshiba commented on src/components/AudioCell.vue
> -          }
debounceですが、[こちらのコメント](https://github.com/Hiroshiba/voicevox/pull/284#issuecomment-932970578)で言及されているように、妙な挙動をひたすら生み出しそうなので、そもそも消す方向に動くと良さそうに感じました。
それと、ここでdebounceが問題になるのは、何も入力していない状態から入力し、IMEを確定させた後高速で複数行を入力した場合なので、一旦無視しても大丈夫だと思います。

2021-10-03 15:57 UTC, Hiroshiba commented on src/store/audio.ts
> +      }
textsは100くらいを想定する感じでどうでしょう。
となると、たしかに問題になりそうなオーダーだと思います。
もしよかったら`INSERT_AUDIO_ITEM`の複数版も作って頂けるととても嬉しいです・・・！

2021-10-04 14:40 UTC, Hiroshiba commented on src/components/AudioCell.vue
> -          }
こちら、もしよかったら戻して頂けると・・・！

2021-10-04 14:59 UTC, merged