読み変更するとイントネーションが文中っぽくなくなる問題の修正
Hiroshiba/voicevox pull request #353
Opened 2021-10-15 14:52 UTC by Segu-g

## 内容

#248 の読み変更における問題を修正しました。

## 関連 Issue

close #248

## スクリーンショット・動画など

## その他

2021-10-15 15:36 UTC, Hiroshiba requested changes
良いですね！！
Request changesですが、コメント追記のお願いだけです！

2021-10-15 15:36 UTC, Hiroshiba commented on src/store/audio.ts
> -      commit("COMMAND_CHANGE_SINGLE_ACCENT_PHRASE", {
`FETCH_AND_COPY_MORA_DATA`を用いるの、スマートな良い実装だと思います！！

ただ、前後のAccentPhrasesと連結してFETCHする必要があるのかは、意図が伝わりづらい気がしました。
文脈が多くて長くなりそうですが、コメントの記載をお願いしたいです。

2021-10-15 15:36 UTC, Hiroshiba commented on src/store/audio.ts
> +      audioStore.mutations.SET_ACCENT_PHRASES(draft, payload);
真上にある`COMMAND_CHANGE_ACCENT_PHRASE_SPLIT`と全く同じ処理内容なのが気になりました。
このプルリクエストで行うべきかわかりませんが、`COMMAND_`関数は誰から呼ばれるかではなく、中で実行することによって名前を決めたほうが良いのかなと少し思いました。

2021-10-16 09:38 UTC, Segu-g commented on src/store/audio.ts
> -      commit("COMMAND_CHANGE_SINGLE_ACCENT_PHRASE", {
a89fa30 でコメントを追加しました。

2021-10-16 14:27 UTC, Segu-g commented on src/store/audio.ts
> +      audioStore.mutations.SET_ACCENT_PHRASES(draft, payload);
MutationをCOMMANDではなく動作で分けると、COMMAND_CHANGE_AUDIO_TEXT等はテキストのセット、テキストとAudioQueryのセット、テキストとAudioQueryのセットみたいに再利用性もないようなMutationが増えそうなので必要なのかわかりません。
Mutationの再利用だけならaudioStoreのMutationを使って欲しいですし

2021-10-16 17:38 UTC, Hiroshiba commented on src/store/audio.ts
> +      audioStore.mutations.SET_ACCENT_PHRASES(draft, payload);
なるほどです。たしかに、少なくとも全Mutationを動作で名付けすると微妙になりそうです。
とはいえ全く同じ処理をする関数が２つ並ぶのも微妙そうです。

実現性は度外視ですが、そもそもMutationやActionなどVuexの概念によって切り分けずに、処理の内容によって好きな位置に関数を書けるようになればよいのかなと思いました。

2021-10-16 17:40 UTC, merged