起動時に簡易的なGPUモードの実行条件に満たない環境の検出とその際にフォールバックする処理の追加
Hiroshiba/voicevox pull request #36
Opened 2021-08-06 02:21 UTC by madosuki

2021-08-08 06:25 UTC, Hiroshiba commented
とても良い機能だと思います。

どうユーザーへ提示すべきか迷っています。

https://github.com/Hiroshiba/voicevox/pull/29 が入れば後から変更可能になるので、GPUを持っている場合はGPUモードで起動、持っていない場合はCPUモードで起動しつつ、ダイアログで「CPU or GPUモードで起動しました」「エンジンの起動モードは画面上部のメニューから変更できます」と案内するのはどうでしょう。

2021-08-08 09:47 UTC, madosuki commented
初回起動時にGPUモードの条件を満たしていればGPUモードへそうでなければCPUモードで起動するメッセージを出して，そのメッセージウィンドウのdetailでメニューバーから切り替えできることを伝える，といった感じに修正しました．

それとメニューから切り替える時に非対応環境であればその旨のメッセージを出して切り替えないという処理を付け加えました．

2021-08-09 15:49 UTC, Hiroshiba reviewed
非対応環境だけれども試したい、もしくは本当は対応環境だけど判定ロジックにミスがある、といった場合のために、非対応環境でもGPUモードを選べるようにしておきたいです。
非対応環境のときにGPUモードを選ぶとアラートが出るのはすごく良いと思うので、「エンジン起動エラーが発生する可能性が高いですが、本当によろしいですか？」などと聞くのはどうでしょう。

2021-08-10 00:03 UTC, madosuki commented on src/utils.ts
> +          a.vendor.indexOf("NVIDIA") !== -1 && a.vram >= 3072
toUpperCase()をするように変更しました．

2021-08-10 00:06 UTC, madosuki commented on src/utils.ts
> +        ? true
三項演算子外してそのままreturnさせるようしました．

2021-08-10 00:08 UTC, madosuki commented on src/utils.ts
> +interface ISysteminformationGraphicsControllers {
これは単純に気付いていませんでした．
自前の型宣言の削除とdetectNvidia関数とimport宣言をbackground.tsに移してutils.tsを削除しました．

2021-08-10 00:11 UTC, madosuki commented
> 
> 
> 非対応環境だけれども試したい、もしくは本当は対応環境だけど（新しいGPUなどなため）判定ロジックで引っかかる、といった場合のために、非対応環境でもGPUモードを選べるようにしておきたいです。
> 非対応環境のときにGPUモードを選ぶとアラートが出るのはすごく良いと思うので、「エンジン起動エラーが発生する可能性が高いですが、本当によろしいですか？」などと聞くのはどうでしょう。

警告メッセージウィンドウを出して確認を取らせるようにしました．

2021-08-10 03:59 UTC, Hiroshiba requested changes

2021-08-10 03:59 UTC, Hiroshiba commented on src/background.ts
> +            type: "question",
`warning`というのもあるそうです。
https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxsyncbrowserwindow-options

2021-08-10 03:59 UTC, Hiroshiba commented on src/background.ts
> +      detectNvidia().then((result: boolean) => {
ここで非同期処理になるので、下の`menu.setActiveLaunchMode(store.get("useGpu", false) as boolean);`が意図しない挙動をしそうです。
async/awaitを使って同期処理にすると`updateProcess();`も減らせて良いかもしれません。

2021-08-10 05:14 UTC, madosuki commented on src/background.ts
> +            type: "question",
warningに変更しました．
それとbuttonの順番を変更しました．これはウィンドウを右上の閉じるボタンで閉じると0が返ってくるため意図せずにモードを変更してしまう恐れがあるからです．

2021-08-10 05:19 UTC, madosuki commented on src/background.ts
> +      detectNvidia().then((result: boolean) => {
menu.ts内のsetOnLaunchModeItemClickedのコールバック関数の返り値をPromise<void>に変更して，background.ts内の該当アロー関数を非同期に変更してローカル変数isChangeableで実際に変更を行うかの確認してから変更を行うようにしました．
それに伴い不要になったupdateProcess関数を削除しました．

2021-08-10 18:24 UTC, Hiroshiba reviewed
LGTM！

package-lock.jsonの変更が大きいようです。
Node.jsのバージョンを`12.18.2`にし、npmのバージョンを最新にしてpackage-lock.jsonを作り直してみてください。
難しそうであれば、一旦このファイルをignoreにしましょう。

2021-08-11 00:43 UTC, madosuki commented
node 12.18.2とnpm 70.20.3でpackage-lock.jsonを作り直しました．

2021-08-11 09:33 UTC, Hiroshiba approved these changes
LGTM！　なかなか長いやり取りとなりましたが、良い機能が入ったと思います。　お疲れさまです。
（文言や挙動は、別プルリクエストとの兼ね合いや全体のデザインと合わせて変更するかもしれません。）

2021-08-11 09:37 UTC, merged