セル追加時に、現在の話速等のパラメータを維持する
Hiroshiba/voicevox pull request #384
Opened 2021-10-23 09:47 UTC by noronoro56

## 内容
現在の仕様では、＋ボタンや文章貼り付けなどで新しいセルが作成されると、パラメータがデフォルトにリセットされます。
同じキャラクターを継続して使う場合は同設定で利用される場合が多いはずなので、現在のセルのパラメータを引き継いで作成されるように変更しました。

## 関連 Issue
ref #383

## スクリーンショット・動画など

https://user-images.githubusercontent.com/92973480/138551381-17adf1a5-abb6-4278-8a8b-bbbf7f30bed5.mp4

## その他

2021-10-24 02:36 UTC, noronoro56 commented
Electronをちゃんと勉強していないので見様見真似ですが、新規セル作成時にパラメータ継承するかどうかのオンオフ機能を作成しました。
「継承する」を選択した状態だと、＋ボタンでの新規セル追加、文章ペーストでの新規セル追加、テキスト読み込みでの新規セル追加時に現在のパラメータ設定を引き継ぎます。
![2021年10月24日11時32分13秒イメージ8551](https://user-images.githubusercontent.com/92973480/138577791-043ff666-caf2-46f0-a678-c43f0de45100.png)
えず

2021-10-30 10:54 UTC, noronoro56 commented
とりあえず一通り修正できたと思います。

>prevAudioItemという引数名でも良さそうなのですが、パラメータの継承元であることがわかるような名前にするのも良いかもと思いました。

分かりやすい名前はぱっと思いつかないですね・・・。

>もしくは引数の意味をドキュメントとして書くのもありだと思います。

ドキュメント、というのは説明コメントを残すという意味でしょうか。

2021-10-30 16:34 UTC, Hiroshiba commented
> ドキュメント、というのは説明コメントを残すという意味でしょうか。

そんな感じです！
↓のような形（jsdoc）で残しておくと良いのかなと思いました。

https://github.com/Hiroshiba/voicevox/blob/3eef9d47b19be36f830b7770c75143a3bfbba14b/src/helpers/previewSliderHelper.ts#L50-L61

ただ他の関数はドキュメントがないので、今回は単純に引数の横に引数のメモを一言コメントするだけでも良いかもです。

名前ですが、baseAudioItemにするとほんのちょっとだけわかりやすくなるかも、と思いました。

2021-10-30 17:25 UTC, noronoro56 commented
試しにjsdocで書いてみようと思いましたが、引数がオブジェクトの場合どのように記述するのかよくわかりませんでした。

>ただ他の関数はドキュメントがないので、今回は単純に引数の横に引数のメモを一言コメントするだけでも良いかもです。

引数に関するコメントは既に入れてありますが、こんな感じでいいでしょうか。
>//引数にprevAudioItemが与えられた場合、prevAudioItemから話速等のパラメータを引き継いだAudioItemを返す
//prevAudioItem.queryのうち、accentPhrasesとkanaは基本設定パラメータではないので引き継がない
//prevAudioItemのうち、textとstyleIdは別途与えられるので引き継がない

>名前ですが、baseAudioItemにするとほんのちょっとだけわかりやすくなるかも、と思いました。
引数名をbaseAudioItemに修正しました。

2021-10-30 22:20 UTC, Hiroshiba requested changes
確かにコメントいただいていました、良いと思います！
見逃していたのですが、最後１点だけよろしくおねがいします・・・。

2021-10-30 22:20 UTC, Hiroshiba commented on src/components/SettingDialog.vue
> +                  ]"
すみません、今気づいたのですがここON/OFFしかないトグルスイッチのがわかりやすそうです・・・！

2021-10-31 09:29 UTC, noronoro56 commented
>トグルスイッチのがわかりやすそうです

修正しました。

2021-10-31 16:31 UTC, Hiroshiba approved these changes
LGTM！！
とても便利な機能だと思います、プルリクエストありがとうございました！
またのプルリクエストをお待ちしています・・・！

2021-10-31 16:31 UTC, merged

2021-10-31 16:33 UTC, noronoro56 commented
こちらこそありがとうございました。