#39 音量調整機能の追加
Hiroshiba/voicevox pull request #41
Opened 2021-08-06 15:57 UTC by k-kuroguro

#39

0.0–1.0の範囲で各セルごとに音量を調整できます.

2021-08-06 22:15 UTC, Hiroshiba commented
コードは完璧だと思います。

そしてすみません、レビューをし終わってから気づいたのですが、このUIを使ったユーザーは、音量が調整された音声が保存されることを望むと思います。
書き出される音声波形の振幅を変更する必要がある、つまり音声合成エンジン側にパラメータを渡してエンジン側で処理するのが良さそうです。

すみません、issue建てたときに気づけませんでした。申し訳ないです・・・

2021-08-23 10:59 UTC, k-kuroguro commented
AudioQueryにvolumeScaleが追加されたので対応しました。

2021-08-23 17:42 UTC, Hiroshiba requested changes
長らくおまたせしてしまいました、修正ありがとうございます。

2021-08-23 17:42 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +        @chaneg="setAudioVolumeScale"
changeの誤字かも？
（ついでに他のsliderのとこも直していただけると・・・！）

2021-08-23 17:42 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +        :max="1"
より音量を大きくしたい方もいるかもしれません。
2くらいまでなら上げても大丈夫なはずです。

2021-08-24 09:25 UTC, k-kuroguro commented
修正しました。

2021-08-24 09:30 UTC, k-kuroguro commented
typosはvueのhtml部分には反応しないみたいですね

2021-08-24 13:11 UTC, Hiroshiba approved these changes
LGTM！
グローバルな音量の値も設定できると喜ばれるかもしれません。
（キャラクターごとのプリセットのほうがいいかも・・・？）

2021-08-24 13:11 UTC, merged