APIクライアントのFactoryを作って、動的にAPIクライアントを変更できるようにする
Hiroshiba/voicevox pull request #420
Opened 2021-10-30 11:07 UTC by yamachu

## 内容

OpenAPIのAPIクライアントは audio.ts でインスタンス化され、Storeで対象のインスタンスに依存するように実装されている。
そのため動的にインスタンスを変更するのが困難であり、StoreのMutationなどにEngineに接続するためのClientの変更を行う関数などを実装をするなどの変更が必要である。
また audio.ts は音声に関する知識だけを持っていてほしいので設計がいびつになることは想像に難くない。

そのため本PRではstoreに直接APIクライアントに依存させず、storeの状態に管理されたFactoryに依存する形に変更する。
この変更により、FactoryのInterfaceを実装したMockのFactoryをStoreのstateに入れることで、EngineなしにUIやStoreの開発も容易になる。（実際の所electron依存のところもInterfaceにする必要はある…）

## 関連 Issue

ref: https://github.com/Hiroshiba/voicevox/issues/220

## スクリーンショット・動画など

## その他

2021-10-30 11:09 UTC, yamachu commented on src/store/audio.ts
> +  _engineFactory: OpenAPIEngineConnectorFactory,
AudioStore に持たせるのもなんか違う気がしている
window.electronとか使ってるのもinfrastructuresとか言う層として扱って、別途Storeを作り、そのStateに突っ込むのがいいのではないかとか思っている

2021-10-30 11:10 UTC, yamachu commented on src/store/type.ts
> +  engineHost: string;
Settingファイルとかへの反映とかは実際にUIから設定を変えられるようにしたりする時に対応予定

2021-10-30 17:14 UTC, Hiroshiba requested changes
engineHostを変更可能にする良い実装に感じました・・・！
ちょっと不安だったのでコメントしてみました。

2021-10-30 17:14 UTC, Hiroshiba commented on src/store/audio.ts
> +  _engineFactory: OpenAPIEngineConnectorFactory,
たしかに別Storeがあっても良いかなと思いました。

vuexの仕様がわからないのですが、`OpenAPIEngineConnectorFactory`をstateに入力しても良いのかがわからないでいます。
Vueの`ref`や`reactive`に入力可能なものであれば良いのかなと思いました。
（`ref(関数)`ってできるんでしょうか・・・？）

2021-10-30 17:14 UTC, Hiroshiba commented on src/infrastructures/EngineConnector.ts
> +import { Configuration, DefaultApi, DefaultApiInterface } from "@/openapi";
`infrastructures`という名前ですが、長めなのと意図が伝わりづらいかもと感じました。
engineとかにするのはどうでしょう？（engineという名前はあまり強い提案ではないです）

2021-10-30 17:32 UTC, yamachu commented on src/store/audio.ts
> +  _engineFactory: OpenAPIEngineConnectorFactory,
FirebaseのUserをStateに突っ込んでいるプロダクトとかも調べてみるとあるので、大丈夫なのかなとは思っていましたが、Documentをちゃんと読んでいないので断言できないですね…
またIssueにStateはShould be serializableだとは言っているので、今回のはあまり良くなさそうではありますね…
https://github.com/vuejs/vuex/issues/757#issuecomment-297668640
（2017年から変わったのかしら…）

2021-10-30 18:12 UTC, yamachu commented on src/store/audio.ts
> +  _engineFactory: OpenAPIEngineConnectorFactory,
こんな感じでStoreCreatorを作って、依存を流し込んだものを外部にexportするという形にしてみましたがどうでしょうか…
https://github.com/Hiroshiba/voicevox/pull/420/files#diff-b86b438c7928773aac473007988ffb602afc8278b8e2226ce784442befb46b0dR117-R124
https://github.com/Hiroshiba/voicevox/pull/420/files#diff-b86b438c7928773aac473007988ffb602afc8278b8e2226ce784442befb46b0dR918

2021-10-30 18:13 UTC, yamachu commented on src/store/audio.ts
> +  _engineFactory: OpenAPIEngineConnectorFactory,
AudioStoreのtestをしたくなったらCreatorもexportして、IEngineConnectorFactoryを実装したものを流し込めば良いのかな、と思ってます

2021-10-30 18:15 UTC, yamachu commented
うーん、このPR、Factoryから引っ張ってくるのと、依存を外部に移すのが混じってしまってるな…

2021-10-31 16:00 UTC, Hiroshiba commented on src/store/audio.ts
> +  _engineFactory: OpenAPIEngineConnectorFactory,
良いと思います！！
ネストが一段増えちゃうのでちょっとだけコーディングが難しくなったかもですが、まあやろうと思えばmutationとかだけ取り出せたりもするので、この形で良いのかなと思いました。

2021-10-31 16:05 UTC, Hiroshiba commented on src/infrastructures/EngineConnector.ts
> +import { Configuration, DefaultApi, DefaultApiInterface } from "@/openapi";
`infrastructures`という名前だけちょっと変えたいかなと思いました。
（意図とか知りたいかもです）

2021-10-31 16:28 UTC, yamachu commented on src/infrastructures/EngineConnector.ts
> +import { Configuration, DefaultApi, DefaultApiInterface } from "@/openapi";
外部との接続があるものに関しては出癖でInfrastructuresにしていました…
別のデザインパターンでの命名なのですが
https://www.google.co.jp/amp/s/www.nuits.jp/entry/easiest-clean-architecture-2019-09%3famp=1
こちらの層分けが参考になると思います

今後リファクタリング等でwindow.electronに直接依存させないようにする際に例えばINativeFileManagerやらILoggerと言う名前でinfraディレクトリに置こうかなぁと思っていたのでこの名前を採用したという感じです

2021-10-31 17:17 UTC, Hiroshiba commented on src/infrastructures/EngineConnector.ts
> +import { Configuration, DefaultApi, DefaultApiInterface } from "@/openapi";
なるほどです、意図があるなら良いと思います・・・！！！

2021-10-31 17:17 UTC, Hiroshiba commented
コンフリクトしていそうなので解消お願いします。

2021-10-31 17:42 UTC, yamachu commented
https://github.com/Hiroshiba/voicevox/pull/420/commits/1be4349b475f8bf2d0315e02f196c4abc5519e80
にてコンフリクト解消しました
コンフリクト部分は
https://github.com/Hiroshiba/voicevox/commit/8d012cd637b1c08bf4065a05c9f5bb0e1c20284f#diff-b86b438c7928773aac473007988ffb602afc8278b8e2226ce784442befb46b0dL434-R484
の箇所のみだったので反映いたしました

2021-10-31 17:50 UTC, Hiroshiba approved these changes
LGTM！！

2021-10-31 17:50 UTC, merged