#415 スタイル毎に別々のアイコンを表示
Hiroshiba/voicevox pull request #421
Opened 2021-10-30 12:35 UTC by MT224244

## 内容

タイトル通りです

## 関連 Issue

close #415 

## スクリーンショット・動画など

![image](https://user-images.githubusercontent.com/25514849/139532690-6dc16555-9573-4c65-9041-201287cfd3b4.png)
![image](https://user-images.githubusercontent.com/25514849/139532726-ebb99dfd-4204-437b-8d60-06c8577759ff.png)

2021-10-30 17:26 UTC, Hiroshiba requested changes
良いですね！！！
１箇所だけコメントしてみました！

2021-10-30 17:26 UTC, Hiroshiba commented on src/background.ts
> -    iconPath,
できる限りviewでディレクトリやファイル名構築の前提を使いたくないので、ここでスタイルごとのiconのパスを指定したほうが綺麗だと思います。
（例えばviewのテストをするときに、同じディレクトリ構造のテストデータを作る必要がなくなり、パスを与えるだけでテストできます。）

2021-10-31 18:23 UTC, MT224244 commented
CharacterInfoにアイコンパス、音声サンプルファイルパスを追加し、viewでパス指定しないようにしました
ついでにパスからBlobを生成してBlobURLで表示していた立ち絵画像を、アイコンと同じように直接パスを入れて表示するようにしました

音声サンプルファイルの順序が間違ったままだった(0がノーマル、2があまあま...になっていた)ので修正しました
#354 で修正したと思っていましたが、 `metas.json` の順序を変えただけで音声ファイルの名前を変え忘れていたようです...

2021-11-01 16:12 UTC, Hiroshiba approved these changes
LGTM！！！

.vueからパス名の前提知識が必要なくなっていてとても良いと感じました！

2021-11-01 16:12 UTC, merged