音声保存時の高度な設定を追加・適用
Hiroshiba/voicevox pull request #426
Opened 2021-10-31 15:54 UTC by y-chan

## 内容

エンジン側に搭載していたものの、使用していなかった音声合成時の高度なオプション(音声のステレオ化・音声のサンプリングレート変更)を有効化しました。
これは音声書き出し時にのみ適用されます。

## 関連 Issue

close #414 

## スクリーンショット・動画など

![image](https://user-images.githubusercontent.com/34832037/139591697-dff08bee-af16-41a6-8468-fa50673a1f92.png)

## その他

製品版resampyが壊れているからか、サンプリングレート変更適用時に音声合成に失敗します。

2021-10-31 17:02 UTC, Hiroshiba requested changes
良いですね！！
どういう仕様にすべきか迷ったのでちょっとコメントしてみました。

2021-10-31 17:02 UTC, Hiroshiba commented on src/store/setting.ts
> +    outputSamplingRate: 24000,
エンジンが返したものをそのまま使える、というのをデフォルト仕様にしたほうが良いかなと思いました。
undefinedの場合はエンジンの値をそのまま使う、というのはどうでしょう・・・？

2021-10-31 17:35 UTC, y-chan commented on src/store/audio.ts
> +          blob = await dispatch("GENERATE_AUDIO", { audioKey, save: true });
orなので大丈夫(キャッシュがないときor出力サンプリングレートが24000ではないときorステレオ出力のとき)だと思っているんですが、私の考え間違いでしょうか....

2021-10-31 17:41 UTC, y-chan commented on src/store/audio.ts
> +
> save時以外もステレオや高サンプリングレートで聞きたい

なるほど、であればそもそも「保存(高度な設定)」ではなく、「音声の生成・保存(高度な設定)」の方がよさそうな上に、設定変更時にすべてのaudio queryを書き換えるのがよさそうですね。

個人的に思っていたのは、UI上で音声合成を行っている(保存ではない)ときは、もっとも速い速度かつメモリを食わない形で音声を生成する方がUXが高いかなと思ったんですが、どうなんでしょうか...

> キャッシュIDを作った後に変更している

おっと、見落としですね...
ただ、設定変更時にすべてのaudio queryを書き換えるなら、そもそもコピーの必要がないので、この部分は不要そうですね。

> `audioQuery.outputSamplingRate!=state.savingSetting.outputSamplingRate`

たしかに...!気づきませんでした....
ただ、これも同上で不要そうです。

> json.stringfyの計算コストがちょっとだけ気になるので、!=のときだけdeepcopyする

そうですね、その方がよさそうです
ただ、これも同上で不要そうです。

2021-10-31 17:44 UTC, y-chan commented on src/store/setting.ts
> +    outputSamplingRate: 24000,
なるほど....
それがよさそうですね....

2021-10-31 18:00 UTC, Hiroshiba commented on src/store/audio.ts
> +          blob = await dispatch("GENERATE_AUDIO", { audioKey, save: true });
ほんとだ！　`||`なので問題なさそうです

2021-10-31 18:22 UTC, Hiroshiba requested changes

2021-10-31 18:22 UTC, Hiroshiba commented on src/store/audio.ts
> +
> 設定変更時にすべてのaudio queryを書き換える

これは先見の明なのですが、設定変更時に保持している全てのAudioQueryを書き換える設計にすると、AudioQueryが増えたときも設定値を反映する必要が出てきます。
AudioQueryが増えるタイミングは至るところに散らばっている（Project LoadとかText Putとか）ので、generate audioのタイミングで変えるようにしたほうが実装とメンテがだいぶ楽だと思います。

2021-10-31 18:22 UTC, Hiroshiba commented on src/store/audio.ts
> +
> UI上で音声合成を行っている(保存ではない)ときは、もっとも速い速度かつメモリを食わない形で音声を生成する方がUXが高いかなと思った

なるほどです！
再生される音と、保存される音は違うことがわかるようなUXになっていれば大丈夫そうです。

2021-10-31 18:22 UTC, Hiroshiba commented on src/components/SettingDialog.vue
> +                <div class="text-h5">保存(高度な設定)</div>
たぶん高度な設定は項目ごとに少数しか無いので、ここは `高度な設定` という題にすると他の項目の設定値も増やしやすいのかなと思いました。

2021-10-31 18:22 UTC, Hiroshiba commented on src/store/setting.ts
> +    outputSamplingRate: 24000,
まあそれはそれでUIがちょっと面倒になるので、とりあえず24000にしても良いのかなと思いました！
エンジンの仕様が何か変わったときにまた再考しましょう。

2021-11-01 16:22 UTC, y-chan commented on src/store/audio.ts
> +
> 再生される音と、保存される音は違うことがわかるようなUXになっていれば大丈夫そう

これを実現するのがかなり難しそうで、サンプリングレートで96kHzでも選ばない限りほとんど影響しないかなと思ったので、共通化させる方向にしました。

2021-11-01 16:23 UTC, y-chan commented on src/components/SettingDialog.vue
> +                <div class="text-h5">保存(高度な設定)</div>
高度な設定、として各設定の文章を少し変更してみました。

2021-11-02 16:50 UTC, Hiroshiba requested changes
すごくわかりやすいロジックだと感じました！！
コンフリクトしているようなので解消お願いします。

2021-11-02 16:50 UTC, Hiroshiba commented on src/store/audio.ts
> +        );
audioItemでdeep copyしているのでaudioQueryはdeep copyしなくてもいいかも

2021-11-02 17:30 UTC, y-chan commented on src/store/audio.ts
> +        );
おっと、修正忘れですね...
修正しておきました...!

2021-11-02 18:40 UTC, Hiroshiba approved these changes
LGTM！！
コードがかなり見やすくなって良かったなと思いました！

2021-11-02 18:40 UTC, merged