Theme
Hiroshiba/voicevox pull request #452
Opened 2021-11-07 06:06 UTC by Patchethium

## 内容

Add theme. At current stage we have only two themes Default and Dark, but anyone can add one easily by creating a json file in `public/themes` referring to other theme config files or the template below. The color format, if not specified, is hex:
```json
{
  "name": "theme name",
  "isDark": "is it a dark theme",
  "colors": {
    "--color-primary": "the primary color",
    "--color-primary-rgb": "primary color in rgb",
    "--color-primary-light": "color for the sliders and scrollbar",
    "--color-primary-light-rgb": "primary-light in rgb",
    "--color-display": "text color",
    "--color-display-rgb": "text color in rgb",
    "--color-display-light": "light text color",
    "--color-display-dark": "dark text color",
    "--color-background": "background color",
    "--color-background-light": "light background, used in buttons on head bar",
    "--color-setting-item": "setting items color",
    "--color-warning": "warning color"
  }
}
```

As you can see, I removed the `secondary` to `display` for the keyword is not used to showing texts. I'm also considering an interactive theme builder in the future.

## 関連 Issue

ref #316

## その他

I may need some help in themes of Markdown pages from who wrote it, I just don't feel like digging into that part. Just tell me what to do and I'll add it to the code. Before that I'll keep this pr a draft.

2021-11-07 10:50 UTC, takana-v commented
github-markdown-cssが色を上書きしているようです。
このコードを追加するとうまくいくかもしれません。
It seems that github-markdown-css is overriding the colors.
Adding this code might work.

(_index.scss)
```css
.markdown-body {
  color: var(--color-display);
}
```

2021-11-08 13:19 UTC, Hiroshiba commented
I think it's an interesting feature!

2021-11-10 11:00 UTC, Patchethium commented
@takana-v That makes sense. But how can I dynamically change the external css file source in javascript? I made a few search but unfortunately none of the answers on stack overflow actually worked.

BTW, the background color from the github markdown css turns out to be only filling the space up to one page, any idea of fixing this?

![image](https://user-images.githubusercontent.com/74458240/141099942-af5bf362-74ce-4c76-9a62-c40866ac2b64.png)

2021-11-10 14:07 UTC, takana-v commented
I think it is difficult to modify the github markdown css.
How about overriding the text and background colors by `_index.scss`?
```css
.markdown-body {
  color: var(--color-display);
  background: var(--color-background);
}
```
![image](https://user-images.githubusercontent.com/44311840/141127782-f7e87fce-ad93-4f05-8595-933b0f378a2b.png)

2021-11-12 14:58 UTC, Patchethium commented
So this means we're getting rid of the github markdown and write the color ourselves, the template above is updated and the following colors are added:

```json
  "color-markdown-color": "the text color of markdown pages",
  "color-markdown-background": "the background color of markdown pages",
  "color-markdown-hyperlink": "the hyperlink color of markdown pages"
```

If that's not a problem it should be good to go now.

2021-11-12 17:11 UTC, Hiroshiba requested changes
It's so great!!! Nice work!!

> I'm also considering an interactive theme builder in the future.

That's very cool.
What kind of things will you be making?

2021-11-12 17:11 UTC, Hiroshiba commented on public/themes/dark.json
> +    "--color-primary": "#0A0A0A",
VOICEVOXの（ダークモード版の）プライマリーカラーの適用に挑戦したいと思っています。
構いませんか？ :-)
I would like to try to apply the ( dark mode version of ) primary color of VOICEVOX.
May I? :-)

2021-11-12 17:11 UTC, Hiroshiba commented on src/App.vue
> +    });
新しく`START_VUEX` actionを作って、これらの処理を全部`START_VUEX`内に書くのはどうでしょう？
How about making a new `START_VUEX` action and put all these processes in `START_VUEX`?

2021-11-12 17:11 UTC, Hiroshiba commented on package-lock.json
> +      "requires": {
packageから`github-markdown-css`が消えているのに、.lockに何かが追加されているのが気になりました。
I noticed that `github-markdown-css` was removed from the package, but something was added to the .lock.

2021-11-13 02:39 UTC, Patchethium commented on package-lock.json
> +      "requires": {
It's npm's work, shouldn't be a problem. If you're not sure about that, you can run `npm uninstall github-markdown-css` on your own machine and copy the package-lock.json here after merging.

2021-11-13 04:49 UTC, Patchethium commented on src/store/setting.ts
> +      if (theme) {
I'm not sure, similar code is everywhere, I don't think it's necessary to use a 3rd party module for a type checking.

2021-11-13 04:52 UTC, Hiroshiba commented on src/store/setting.ts
> +      if (theme) {
あ、すみません！assertではなく`if () raise Error`でした！
Oh, sorry, it was `if () raise Error`, not `assert`!

2021-11-13 04:53 UTC, Patchethium commented on public/themes/dark.json
> +    "--color-primary": "#0A0A0A",
Suit yourself, the reason I put themes in experimental function is I haven't decided the colors.

どうぞ、そもそも実験的な機能に置いたのも私が色を決められないためです。

2021-11-13 05:24 UTC, Patchethium commented
> That's very cool.
> What kind of things will you be making?

Something just like [quasar's](https://quasar.dev/style/theme-builder#introduction) theme builder, maybe with a light weight preview and export/import function.

2021-11-13 13:34 UTC, Hiroshiba commented on package-lock.json
> +      "requires": {
Okay!

2021-11-13 13:47 UTC, Hiroshiba approved these changes
LGTM！！

エクスポート・インポート機能！！素晴らしいと思います！
軽量なプレビュー機能もあるととても便利だと思います、良いですね！
Export/Import feature! I think it's great!
I think a lightweight preview feature would be very useful too, good!

またのプルリクエストをお待ちしております。
We look forward to your pull requests again.

2021-11-13 13:47 UTC, Hiroshiba commented on src/type/preload.d.ts
> +  colors: {
TypeScriptに詳しくないのですが、もしかしたらここは以下のようにすることで、１回の定義で済ませられるかもしれません。
I'm not familiar with TypeScript, but you might be able to change this here.
```ts
{ [K in ThemeColorType]: string }
```

2021-11-13 13:47 UTC, merged