自動ビルド時に製品版のリソースを取り込むようにGitHub Actionsを書き換える
Hiroshiba/voicevox pull request #465
Opened 2021-11-10 17:45 UTC by y-chan

## 内容

題の通り

## 関連 Issue

close #440 

## リザルト

自動ビルド待ち

## その他

2021-11-11 09:01 UTC, y-chan reviewed
とりあえずレビューにおいて気になりそうな点を抜き出してみました。
bashなんかは手探りで書いたので、もっときれいな方法をご存じであれば、指摘等していただければ幸いです。

2021-11-11 09:01 UTC, y-chan commented on .github/workflows/build.yml
> +          file: artifact/*.7z.*
実際に自動でリリースにアップロードするのを実行してみると、この部分にミスがあることが発覚したので、変更しました。

2021-11-11 09:30 UTC, y-chan commented on .github/workflows/build.yml
> +          cp README.txt public/policy.md
`README.md`と`ACKNOWLEDGMENTS.md`を改行(echo)を挟んで結合し、`README.txt`(旧`README_SOFTWARE.txt`)として書き出します。
`README_LIBRARY.txt`は廃止しました。
また、`policy.md`も同一のものとみなしたので、ただ単にコピーしています。

2021-11-11 14:49 UTC, Hiroshiba commented on .github/workflows/build.yml
> +            if [ "$FILEPATH" != "." ]; then
`find . -maxdepth 1 -mindepth 1`とかにすると`.`を失くせるかもです

2021-11-11 15:10 UTC, Hiroshiba requested changes
良いですね・・・！！
最後の`;`があったりなかったりするのがちょっと気になりました。
（他のstepが;無しが多そうなので、無い方に合わせるのが良さそう？）

2021-11-11 15:10 UTC, Hiroshiba commented on .github/workflows/build.yml
> +        run: patch -u vue.config.js < build/vue.config.js.patch
ダミーのREADME.txtをbuildディレクトリの下あたりに作っちゃうのが手っ取り早いかなと思いました！

2021-11-11 15:10 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          mv "${INSTALLER_NAME}" ${INSTALLER_NAME// /.}
これ（.で置き換え）もコメントで書き残していると優しいと思います。

2021-11-12 17:15 UTC, y-chan commented
ご指摘の点の修正・コメントの追加等完了しています。
レビューしていただければ幸いです...!

2021-11-12 17:56 UTC, Hiroshiba approved these changes
LGTM！！！
リリース作業がかなり短縮できそうです、ありがとうございます！！！

2021-11-12 17:56 UTC, merged