[ReFix]Alt+F4で確認ダイアログを出すやつがLinuxでバグってたので修正
Hiroshiba/voicevox pull request #471
Opened 2021-11-12 11:37 UTC by madosuki

## 内容

以前、ショートカットキーでのウィンドウを閉じる挙動をジャックする形で修正をしましたが、これだとLinuxでは上手く動作しないのがわかりましたので```window closeイベント```と```app before-quit```イベントを使った実装に変更してみました。

[https://qiita.com/hoto17296/items/72d3526bef332f9ce027](https://qiita.com/hoto17296/items/72d3526bef332f9ce027)によるとCommand-QとAlt+F4 or Command-Wで閉じた時に発火するイベントの順番が違うっぽいので若干面倒な実装になっています。
Mac持ってないのでCommand-Q辺りの挙動を確認できていないです。

尚この実装でも予期せぬ終了に対応できないので #458 はcloseしません。

## 関連 Issue

ref #447
ref #458 

## スクリーンショット・動画など

## その他

2021-11-12 15:18 UTC, Hiroshiba requested changes
なるほど、終了処理はかなり複雑なんですね・・・！
制御変数を２つ使って終了経路が３つ（Vue側のバツボタン、cmd+Q、cmd+W）に対応される実装でしょうか。
ちょっと複雑になりそうだったので、書かれている資料を元に、制御変数を使わないで、経路３つを同じように処理する機構を考えてみました・・・！

まずcmd+Qとcmd+Wですが、どちらも`win.on(close)`で処理するとスマートな気がします。
cmd+Qの方は最初に`app.before-quit`が呼ばれますが、スルーしても問題ないような実装にすると良さそうです。
（現状だとbefore-quitでエンジン停止処理が書かれているので、これをwill-quit辺りに移すとbefore-quitはスルーできるのかなと思っています）

次にVueのバツボタンですが、ちょっとvuexの関数をいじります。
vuexのCLOSE_WINDOWを、ダイアログを出して閉じれるか判定するCAN_CLOSE_WINDOWと、app.closeを実行するだけのCLOSE_WINDOWに分けます。
そしてbackground.ts側のCLOSE_WINDOWでは、win.close()だけを実行するようにします。
この状態で、バツボタンを押すと今のようにCLOSE_WINDOWを実行すれば、他の2経路と同じく`win.on(close)`に来るはずです。

あとは`win.on(close)`内で、Vuex側のCAN_CLOSE_WINDOWをawaitで実行し、閉じてよければ何もせず、閉じて行けなければevent.preventを実行するようにすれば、スマートかなと思いました。

ちょっと説明が下手くそで申し訳ないのですが、どうでしょう・・・？

2021-11-13 06:30 UTC, madosuki commented
> あとは`win.on(close)`内で、Vuex側のCAN_CLOSE_WINDOWをawaitで実行し、閉じてよければ何もせず、閉じて行けなければevent.preventを実行するようにすれば

RendererからMainの場合はawaitで返り値取れますが、MainからRendererの場合はonを使う必要があって同期処理ができないのでこれは無理かなと思います。

Cmd+Qは```app.quit()```、Cmd+Wは```win.close()```を実行しているのでここら辺の区別と、前述した通りにMainからRendererへの処理が同期的にできないので、後から```win.close()```、```win.destroy()```、```app.quit()```を呼ぶことになりそうですが、どれであってもcloseイベントを通るので制御変数無しでやるのは厳しい感じがします。

2021-11-13 06:33 UTC, madosuki commented
微修正してごちゃごちゃ感は多少減らしましたがあまり良い感じの実装が思いつきません。

2021-11-13 19:35 UTC, Hiroshiba commented
> MainからRendererの場合はonを使う必要があって同期処理ができない

な、なんと･･･本当ですね･･･。
すみません、仕様をよく知りませんでした。

整理されたコードを眺めていて思ったのですが、Cmd+Qのapp.quit()もCmd+Wのwin.close()も行き着く先はアプリ終了なので、どちらが起因かは区別する必要は無いのかなと思いました。
なのでどちらもpreventしてしまって、`CHECK_EDITED_AND_NOT_SAVE`を呼べば良いのかなと。

考えている流れはこんな感じです。
制御変数`willClose`があるとして、

- （main側のonで終了イベントを検知した場合）`if(!willClose) event.prevent()`
- renderの`CHECK_EDITED_AND_NOT_SAVE`
- mainの`CLOSE_WINDOW`
- `willClose=true; app.emit("window-all-closed"); win.destroy();`

2021-11-14 01:20 UTC, madosuki commented
コメント内容に沿う形に修正できたと思います。

2021-11-14 10:44 UTC, Hiroshiba requested changes
おーすごいシンプルですね！！！
一点だけ気になったのでコメントしてみました！

2021-11-14 10:44 UTC, Hiroshiba commented on src/background.ts
> +  }
ここ、returnがあったほうがいいかもと思いました。
（下に書いてあるエンジン停止処理が実行されてしまいそうなので）

2021-11-14 12:22 UTC, madosuki commented on src/background.ts
> +  }
修正しました。

2021-11-14 13:25 UTC, Hiroshiba approved these changes
LGTM！！
知識不足で明後日な方向の提案をしてしまってすみませんでした。
議論に真摯に受け答えして頂いてありがとうございました！！
コンパクトで良い実装にたどり着けたかなと思います・・・！

2021-11-14 13:26 UTC, merged