デフォルトに戻すボタンの追加
Hiroshiba/voicevox pull request #472
Opened 2021-11-12 14:27 UTC by nogino52

## 内容

## 関連 Issue

## スクリーンショット・動画など

## その他

2021-11-12 15:35 UTC, Hiroshiba requested changes
プルリクエストありがとうございます！
素晴らしいです、今の実装に完璧に沿っている全く問題のない実装だと思います・・・！！！

１つだけ、誤操作やなんとなく押しちゃったときにいきなり初期値に戻ってしまうとちょっと混乱するユーザーもいるかもなので、「初期値に戻します。よろしいでしょうか？」といった内容のダイアログを出すのをお願いしたいです。
（こちらが参考になるかもしれません。
https://github.com/Hiroshiba/voicevox/blob/989659a1ca08e4901c95c542993af63d51c8c184/src/components/SettingDialog.vue#L414 ）

2021-11-13 02:26 UTC, nogino52 commented
ご指摘いただいた確認ダイアログの追加と、
生配信で言及されていたツールチップの表示時間の短縮(0.5s)、ボタン色の変更を行いました。

（ボタン色ですが、適当なものが見つからなかったためgrey-6にしました。問題があれば変更します。）

![voicevox 2021_11_13 11_21_24](https://user-images.githubusercontent.com/91000720/141602324-733eb13f-2216-46e6-84f5-37a4c6cec88f.png
![voicevox 2021_11_13 11_21_58](https://user-images.githubusercontent.com/91000720/141602334-5983596c-dc61-4b8e-9299-595ff258a8d3.png)
)

2021-11-13 13:29 UTC, Hiroshiba requested changes
とても細かいことですが、ホバー時にボタンの色が濃くなるとより一層わかりやすいかなと思いました！
（他の機能を実装中等でちょっと面倒でしたら言っていただけると！）

2021-11-13 20:01 UTC, Hiroshiba requested changes

2021-11-13 20:01 UTC, Hiroshiba commented on src/components/HotkeySettingDialog.vue
> +          "ショートカットキーの設定を初期値に戻します。<br/>本当に戻しますか？",
ついでなのですが、何のactionかわかるようになっていると優しいかもと思いました。

2021-11-14 00:15 UTC, nogino52 commented on src/components/HotkeySettingDialog.vue
> +          "ショートカットキーの設定を初期値に戻します。<br/>本当に戻しますか？",
いろいろと確認漏れがありました。
お手間を取らせてしまってすみません。

こちらのactionなのですが、何のactionかわかるようにするのはどうすればよいのでしょうか……？
変数名は他の関数と統一してありますし、コメントを書けばいいんでしょうか？
コメントを書くにしても、どのような内容をコメントすればいいのかいまいちわからないので、教えていただければと思います。

至らず申し訳ありません。

2021-11-14 10:38 UTC, Hiroshiba commented on src/components/HotkeySettingDialog.vue
> +          "ショートカットキーの設定を初期値に戻します。<br/>本当に戻しますか？",
いえいえ！

あ、言葉足らずでした！
ユーザーがなんのactionをデフォルトに戻そうとしていたか一瞬忘れて不安になるかもなので、
操作「（action名）」のショートカットキーを初期値に〜、といった案内があると優しいかも、という意図でした。

2021-11-14 11:12 UTC, nogino52 commented on src/components/HotkeySettingDialog.vue
> +          "ショートカットキーの設定を初期値に戻します。<br/>本当に戻しますか？",
そういうことでしたか！
「xxxのショートカットキーを初期値に戻します。
本当に戻しますか？」という形に変更しました。

2021-11-14 13:02 UTC, Hiroshiba approved these changes
LGTM！！良い実装とUIだと感じました！
またのプルリクエストをお待ちしております・・・！

2021-11-14 13:03 UTC, merged