入力欄が一つだけになった時は削除しない #28
Hiroshiba/voicevox pull request #48
Opened 2021-08-07 09:20 UTC by mkgask

テキスト欄が全部消えてしまう #28 の実装です。

入力欄が全部消えることにメリットが特に無いと思うので、最後の一個は消えない形が私も良いと思います。

2021-08-07 10:12 UTC, Hiroshiba commented on src/components/AudioCell.vue
>        // エラー防止のためにまずwillRemoveフラグを建てる
このあたりのコメントが浮いてしまうので、後続の開発に混乱が生じるかもしれません。
念の為コメントも移動したほうが良さそうです。

2021-08-07 10:16 UTC, Hiroshiba reviewed
良さそうです。
テキスト欄が１つだけの場合は消去ボタンが無効になっていると更にユーザーフレンドリーになりそうです。

2021-08-07 12:28 UTC, mkgask commented
テキスト欄1つの時はグレーの押せないゴミ箱アイコンにする方向で考えたんですが、もしかして2個以上の時だけ表示される方が分かりやすいでしょうか？
初回起動時にゴミ箱アイコン気付いたけど押しても反応がない・・・はファーストインプレッション良くない気がしました。
それよりは2個以上になると出てきて1個になるまで押せるほうが良いかもです。

2021-08-07 14:37 UTC, mkgask commented
![record_20210807_232256](https://user-images.githubusercontent.com/8291395/128603630-2877271c-e719-46f6-af94-b5a7cfca2506.gif)
![record_20210807_232544](https://user-images.githubusercontent.com/8291395/128603633-a4949e90-4326-4bfa-af4b-2dada39fdc26.gif)
比べてみるとゴミ箱アイコンに気付いてもらえないほうが問題っぽいですね。

2021-08-08 08:01 UTC, Hiroshiba commented
たしかに、最初に起動された方に混乱を与えてしまいそうです。
disableではなく、非表示にしましょう。

2021-08-08 14:18 UTC, Hiroshiba requested changes
別のプルリクエストでUIライブラリを変更した関係でコンフリクトが起こっていそうです。

2021-08-08 14:18 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +      return 1 < audioKeys.value.length ? true : false;
三項演算子にしなくても大丈夫なはず？
```suggestion
      return 1 < audioKeys.value.length;
```

2021-08-08 14:18 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +  }
消し忘れかもです

2021-08-08 16:41 UTC, Hiroshiba approved these changes
LGTM！　良い提案でした！

2021-08-08 16:41 UTC, merged