音声の再生デバイスを変更できるようにする
Hiroshiba/voicevox pull request #492
Opened 2021-11-19 09:36 UTC by nogino52

## 内容
音声の再生デバイスを変更する設定を追加しました。
再生するたびに利用可能なデバイスを探索し、見つからなかった場合はデフォルトのまま再生します。

setSinkIdがexperimentalな機能であるためか、typescriptに(?)認識されておらず怒られてしまったため、
変則的な方法で対応することになってしまいました。
また、setSinkIdはChromiumでサポートされているため使えるのですが、
今後のバージョンアップ等で変更になる可能性があります。

## 関連 Issue
close #459

## スクリーンショット・動画など

![voicevox 2021_11_19 18_20_04](https://user-images.githubusercontent.com/91000720/142598082-798b8b3d-9b01-4e5e-a177-6287e167f3be.png)
![voicevox 2021_11_19 18_20_20](https://user-images.githubusercontent.com/91000720/142598112-4b86cff1-6517-48c4-ad2a-c6f19d3f9edd.png)

## その他

2021-11-19 14:41 UTC, Hiroshiba requested changes
良いですね！！
ちょっとだけ気になった箇所があったのでコメントしてみました！

2021-11-19 14:41 UTC, Hiroshiba commented on src/store/audio.ts
> +          }
deviceが見つからなかったらエラーが出るようになっていると便利かもと思いました。
ここでthrow Error()すると.vue側でダイアログが出るようになっていたと思うので、一度試してみてもらえると嬉しいです。

もしそのエラーが出なければ、追加していただくか、もしくは//FIXMEコメントとしてエラーダイアログが出るようにすることをコメント頂けると！

2021-11-19 14:41 UTC, Hiroshiba commented on src/components/SettingDialog.vue
> +        }
computedのgetで、handleSavingSettingChange(= set)を実行するのはちょっと不思議な感じがしました。
watchあたりを使うのが一般的かもですが、そうすると一致するdevice判定を２回書く必要が出てしまいますね･･･

一致するdevice判定をcomputedで書いて、その値を元にgetとhandleSavingSettingChangeするのを別々に書くか、
今の実装のままここにコメントで、見つからなければdevice設定を変更することを`get: () => {`の下辺りに書いて頂ければ！

2021-11-19 16:34 UTC, nogino52 commented on src/store/audio.ts
> +          }
エラーを投げてみましたが、コンソールに表示されるだけでダイアログは出ないようでしたので、
エラーダイアログが出るように修正しました。

2021-11-19 16:36 UTC, nogino52 commented on src/components/SettingDialog.vue
> +        }
いろいろと試してみましたが、よくわからなかったのでコメントを書いておきました。
申し訳ありません。

2021-11-20 12:58 UTC, Hiroshiba approved these changes
LGTM！！
良い機能・実装だと思います！またのプルリクエストをお待ちしております・・・！

2021-11-20 12:58 UTC, Hiroshiba commented on src/store/audio.ts
> +          throw new Error(err);
ちなみにここに来る場合ってどんなときでしょうか？👀

2021-11-20 12:58 UTC, merged