`IS_UNSET_DEFAULT_STYLE_IDS`をリファクタリング
Hiroshiba/voicevox pull request #510
Opened 2021-11-25 17:51 UTC by y-chan

## 内容

`IS_UNSET_DEFAULT_STYLE_IDS`などをリファクタリングし、`IS_UNSET_DEFAULT_STYLE_ID`に改名したうえで、speaker uuidを引数として各話者ごとにデフォルトスタイルがセットされているか否かを取得できるようにしました。
また、その改変に伴って必要な周辺の修正も行いました。

これによって、新規キャラが増えた際に、再度デフォルトスタイルについて問うようになります。

## 関連 Issue

- close #509 
  - 正確にはこのIssueに対する解決策ではないです。UIが表示されなくなる問題に関しては、 #501 で対応すべきかなと考えたので、ここでは対応していません。

## スクリーンショット・動画など

## その他

2021-11-25 23:22 UTC, y-chan commented
@Hiroshiba #509だけに対処する予定でしたが、依存等々の関係上#501も含めてまとめて対処しました。
リリース直前に見つかったバグやらなんやらを詰め込んで修正しているので若干変更量が多い上、ゴリ押し気味なところもありますが、よろしくお願いします。

2021-11-25 23:48 UTC, Hiroshiba requested changes
PRありがとうございます！！
一箇所だけ意図を確認したくてコメントして、ついでにいくつかコメントしてみました！

2021-11-25 23:48 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +              <template v-if="characterInfo.metas.styles.length > 1">
意図のコメントがあるとわかりやすいかもと思いました。
（デフォルトスタイルが一部だけ設定されている場合に表示されてしまう、とかでしょうか・・・？）

2021-11-25 23:48 UTC, Hiroshiba commented on src/views/Home.vue
> +      if (characterInfos.value) {
何も入っていないときを想定しているのかしていないのかの意図を伝えるために、raiseの方が良いかもと感じました

2021-11-25 23:48 UTC, Hiroshiba commented on src/components/DefaultStyleSelectDialog.vue
> -      const defaultStyleIds = props.characterInfos.map((info, idx) => ({
ちょっとだけ意図がわかりづらいと感じたので、設定が既存であれば上書き、なければ足す、的なコメントを書いて頂けると！

2021-11-26 04:04 UTC, y-chan commented
@Hiroshiba 遅くなりました、コメントをいくつか追加してみたり、レビューに従って変更してみたりしました。
再レビューお願いします...!

2021-11-26 08:02 UTC, Hiroshiba approved these changes
LGTM！！
素早い対応ありがとうございます！！

2021-11-26 08:02 UTC, merged