#75 メニューをVue側に移動
Hiroshiba/voicevox pull request #84
Opened 2021-08-13 18:32 UTC by MT224244

close #75 

ダイアログもVue側で開くようにしました

![image](https://user-images.githubusercontent.com/25514849/129403209-df86e722-6bab-4df2-9c73-ce27d92ffcd5.png)
![image](https://user-images.githubusercontent.com/25514849/129403238-e4601285-3cab-4559-a36f-4c24272bd376.png)
![image](https://user-images.githubusercontent.com/25514849/129403280-8c351b8b-5201-4de2-be38-d6ffe6a94ffb.png)
![image](https://user-images.githubusercontent.com/25514849/129403358-2b2d0896-3269-4c28-8c3d-94e4b11b4861.png)

2021-08-15 11:13 UTC, MT224244 commented
メニューをクリックで展開後、閉じるまではホバーで自動展開されるように実装を見直しました
これでよくあるメニューの挙動とほぼ同等のものになったと思います

https://user-images.githubusercontent.com/25514849/129476348-eb039ec8-4b09-4b09-a08c-62f5bc6abbc9.mp4

2021-08-15 16:00 UTC, Hiroshiba requested changes
素晴らしい機能だと思います。
実装が一部重複していたりしますが、まだどういう機能がほしくなるかわからない状態なので、そのままで良いと思いました。

2021-08-16 00:09 UTC, MT224244 commented on src/components/MenuButton.vue
> +  <q-badge
q-btnにした場合、原因不明のエラーが発生してしまったためです
動作上は影響が無さそうでしたが、DevToolsにエラーが出続けるのは良くないなと思い試行錯誤した結果、q-badgeにすると消えたのでそのまま使用しています
エラーの根本的な解決には至っていません

![image](https://user-images.githubusercontent.com/25514849/129496664-429fed2c-58b6-4b76-ab3c-f41072d1dd42.png)

2021-08-16 00:27 UTC, MT224244 commented on src/components/MenuItem.vue
> +      );
ホバーでメニューの選択状態を切り替えると、閉じられたメニューの子の選択状態は変化しないので下の動画のように開かれたままになってしまいます
そのため、自分が選択状態でなくなった時に子の選択状態をリセットしています

https://user-images.githubusercontent.com/25514849/129497319-880dc971-8eb8-411b-bdd7-0630a6a5fcea.mp4

2021-08-16 11:14 UTC, MT224244 commented
指摘箇所の修正ついでに、少し気にされていたSCSS部分のマジックナンバーを変数として持つよう修正しました

2021-08-16 12:08 UTC, Hiroshiba commented on src/components/MenuItem.vue
> +      );
なるほどです。

2021-08-16 12:34 UTC, Hiroshiba approved these changes
LGTM！

ウィンドウについてる最小化や閉じるボタンもこのMenuBarに追加したくなりますね。
ということでissueを作ってみました。 https://github.com/Hiroshiba/voicevox/issues/104

2021-08-16 12:34 UTC, Hiroshiba commented on src/components/MenuButton.vue
> +  <q-badge
なるほどです。コメントがあればとりあえずOKです。

2021-08-16 12:34 UTC, Hiroshiba commented on src/styles/_index.scss
> +$menubar-height: 24px;
なるほど、良いですね。

2021-08-16 12:35 UTC, merged