GitHub Actionsにタイポ検知を追加
Hiroshiba/voicevox pull request #93
Opened 2021-08-15 02:42 UTC by shirayu

https://github.com/Hiroshiba/voicevox/pull/65#issuecomment-898911701 の実装です

2021-08-15 16:06 UTC, Hiroshiba requested changes
LGTM！　いいですね。
![image](https://user-images.githubusercontent.com/4987327/129484809-506c1877-827d-4668-b24a-9cbd40350adc.png)

スペルミスが発生した場合どういう対処をすればいいか、READMEにちょっとした追記をお願いします。

2021-08-16 08:55 UTC, shirayu commented
> LGTM！　いいですね。
> ![image](https://user-images.githubusercontent.com/4987327/129484809-506c1877-827d-4668-b24a-9cbd40350adc.png)
> 
> スペルミスが発生した場合どういう対処をすればいいか、READMEにちょっとした追記をお願いします。

追記しました！

2021-08-16 11:56 UTC, Hiroshiba commented on README.md
> +[設定ファイルの説明](https://github.com/crate-ci/typos#false-positives)に従って```_typos.toml``を編集してください．
`の数が多そうです
```suggestion
[設定ファイルの説明](https://github.com/crate-ci/typos#false-positives)に従って`_typos.toml`を編集してください．
```

2021-08-16 13:22 UTC, shirayu commented on README.md
> +[設定ファイルの説明](https://github.com/crate-ci/typos#false-positives)に従って```_typos.toml``を編集してください．
おっとすみません，修正しました

2021-08-16 13:27 UTC, Hiroshiba approved these changes
LGTM！

2021-08-16 13:27 UTC, merged