音高の値をSliderの上に表示する
Hiroshiba/voicevox pull request #94
Opened 2021-08-15 06:34 UTC by mes51

close #79 

マウスカーソルがSliderの上にいるときに音高の値を表示するようにしました。
該当IssueではQSliderのlabelをCSSで変更して利用してはどうか、という事でしたが、値の桁数が多くなると隣のSliderに被ってしまうため、Slider上部に表示するようにしてみました。

## Screenshot

![image](https://user-images.githubusercontent.com/936617/129469240-bbcdf327-d321-4234-afd8-750ef72d680b.png)

## その他

音高の表示に関しては完全にViewの見た目のみの状態のためdata/methodsを使っていますが、Storeに追加してsetupを使うべき、等があれば指摘いただけると助かります

2021-08-15 17:02 UTC, Hiroshiba requested changes
良さそうです！

イントネーションの一番左のラベルの左端が切れていました。見切れなくできると嬉しいです。

2021-08-15 17:02 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +        moraIndex: -1,
あ、このプロジェクトはVue3のComposition APIで書かれているので、そちらに統一してみてください。
おそらく、setup()の中に

```ts
const pitchLabel = reactive({
  visible: false,
  panning: false,
  accentPhraseIndex: -1,
  moraIndex: -1,
})
```

と書けば、`this.`なしでpitchLabelにアクセスできると思います。
（template内からも見れるようにするには`setup()`関数のreturnにpitchLabelを追加する必要があります。）

https://v3.ja.vuejs.org/api/basic-reactivity.html#reactive

2021-08-16 11:19 UTC, mes51 commented on src/components/AudioDetail.vue
> +        moraIndex: -1,
なるほど。これを見つけられなくて、どうしたものかと言うことでdata/methodsを使用していました...
こちらに修正します

2021-08-16 11:38 UTC, mes51 commented
> イントネーションの一番左のラベルの左端が切れていました

こちらにつきまして確認できました。ただ、修正方法についてラベルを右に寄せるか、`.accent-phrase-table`の左にpaddingを足すかどちらが良いかお聞きしたいです(個人的には`.accent-phrase-table`の左にpaddingを足す方が違和感が少なくていいかなと思います

## ラベルを右に寄せるパターン

![image](https://user-images.githubusercontent.com/936617/129556985-4ab93616-eade-4cf7-8e1f-4aad5903e32e.png)

## 左にpaddingを足すパターン

![image](https://user-images.githubusercontent.com/936617/129557322-9e72d715-6f6d-40d3-b78b-e3f8432627c3.png)

2021-08-16 13:30 UTC, Hiroshiba commented
僕も同意見で、paddingを付ける方が良さそうだと思いました。
そちらの方針で実装をお願いします。

2021-08-16 13:42 UTC, Hiroshiba approved these changes
LGTM！　良い実装だと思いました。

2021-08-16 13:42 UTC, merged