#15 GitHub Releaseから分割したインストーラーをダウンロードする
Hiroshiba/voicevox pull request #95
Opened 2021-08-15 07:29 UTC by HyodaKazuaki

#15 の対応です。

# できること

以下の3つの手段で分割ダウンロードとインストールを可能にしています。

* `electron-builder`で作成できるインストーラー形式を`nsis-web`にして、インストーラーを実行ファイル(拡張子`.exe`)と圧縮データファイル(拡張子`.7z`)に分ける
* 圧縮データファイルを別の手段で適当な大きさに分割する
* インストーラーにカスタムスクリプトを仕込み、インストール直前に分割した圧縮データファイルのダウンロードと結合を行う

この機能を実装したインストーラーを以下のGitHub Releaseで配布していますのでご確認ください。

https://github.com/HyodaKazuaki/voicevox/releases/tag/0.3.1

# インストーラー作成手順

以下の手順でインストーラーを作成することができます。

1. 圧縮データファイルの分割数を予測し、`installer.nsh`の7行目や15行目などのファイル指定を変更する
  以下の4箇所の変更が必要です。
  https://github.com/Hiroshiba/voicevox/commit/ce7f49857c13977cec4378e850e913ec6955c2e7#diff-9509ebc5f256196a628f79001406ea5ab1aab64728fbc20a5501061d1dd31eb9R7
  https://github.com/Hiroshiba/voicevox/commit/ce7f49857c13977cec4378e850e913ec6955c2e7#diff-9509ebc5f256196a628f79001406ea5ab1aab64728fbc20a5501061d1dd31eb9R15
  https://github.com/Hiroshiba/voicevox/commit/ce7f49857c13977cec4378e850e913ec6955c2e7#diff-9509ebc5f256196a628f79001406ea5ab1aab64728fbc20a5501061d1dd31eb9R29
  https://github.com/Hiroshiba/voicevox/commit/ce7f49857c13977cec4378e850e913ec6955c2e7#diff-9509ebc5f256196a628f79001406ea5ab1aab64728fbc20a5501061d1dd31eb9R37-R39
2. `npm run electron:build_pnever`を実行する
3. `dist_electron/nsis-web`配下に作成された`voicevox-<VERSION>-x64.nsis.7z`を何らかの方法で分割する
  今回は https://github.com/HyodaKazuaki/file-split の`split.py`を利用し、1GBごとにファイルを分割しました。
4. 分割したファイルと`VOICEVOX Web Setup <VERSION>.exe`をGitHub Releaseで公開する

# できないこと

* 圧縮データファイルの分割数を予測して`installer.nsh`を書き換えること
  経験的に分割数を予測できるかと思いますが、現時点では一度ビルドして圧縮データファイルの大きさ(分割数)を確認してから手動で書き換える必要があります。
* GitHub Actionsへの対応
  このPRでは対応できていませんが、少なくとも[インストーラー作成手順](インストーラー作成手順)の2~4を自動化することは可能だと思われます。

2021-08-15 17:36 UTC, Hiroshiba commented
なるほど、nsis-webでできるのはすごく良いですね！

releasesにある.exeを自分の環境で動かしてみたところ、結合でエラーが出るようでした。こちらは想定内でしょうか。
![image](https://user-images.githubusercontent.com/4987327/129487204-87fcdf38-1589-46f9-af52-a2dceb7b0ce0.png)

分割インストーラが現実的に見えてきたのはすごく魅力的です。

2021-08-16 03:24 UTC, HyodaKazuaki commented
> releasesにある.exeを自分の環境で動かしてみたところ、結合でエラーが出るようでした。こちらは想定内でしょうか。

おそらく、ウイルス対策ソフトの影響でインストーラーがダウンロードしたファイルが削除されているのではないかと思います。
インストーラーを起動するとInetcプラグインのダウンロードダイアログが開くかと思いますが、その際`%Temp%`の中に`voicevox-0.3.1-x64.nsis.7z.0`、`voicevox-0.3.1-x64.nsis.7z.1`、`voicevox-0.3.1-x64.nsis.7z.2`がダウンロードされているか確認いただけますか？
ダウンロード後削除されているような挙動を示すようであれば、一旦ウイルス対策ソフトを止める必要があるかもしれません。
とりあえず、ファイル結合のエラーメッセージを表示することができるようにカスタムスクリプトを修正しましたので、今一度GitHubのReleaseよりインストーラーをダウンロードして試してみてください。

GitHub ActionsのCIが失敗している件ですが、これは`npm run electron:build_pnever `をLinux環境で実行するとLinux向けにビルドが走るためだと思われます。
CIのOSイメージをWindows系に変更するとCIが通るかと思います。

2021-08-16 08:10 UTC, Hiroshiba commented
詳細にありがとうございます。次はなぜかちゃんとインストールまで進みました。

インストールは.exeをダブルクリックするだけなのでとても便利ですね。
素晴らしいです。ぜひ取り入れたいです。

2021-08-16 08:10 UTC, Hiroshiba commented
リリースの手順が煩雑化しそうなので、いったん整理してみます。

```
今まで
build → publish（google driveにアップロード）

この場合
build → （分割数が変わりそうであればコード変更） → 7z分割 → publish（github releaseにアップロード）
```

electron-builderには確かpublish機能があってgithub releaseにアップロードできるんですよね。
いったんgithub actions化するかは置いといて、分割とアップロードを自動化できるとかっこよさそうに思います。

（コード変更の部分の自動化は、nsisスクリプトに詳しくならないと難しそうなので、一旦このままで良いと思います。）

2021-08-16 08:11 UTC, Hiroshiba commented
こちらからの要望をまとめます。

1. テストが通るようになっていることは必須です。Linuxでもビルドできるようにするのがベストだと思いますが、僕もやり方がわかりません。win項目を無視するようなコマンドを探すか、windows用のビルドコンフィグを分けて`npm run electron:build --config [windows用のビルドconfig]`とするなどの方法がありそうです。（--configを与える方法は[こちら](https://www.electron.build/configuration/configuration.html)です）
2. electron:buildを叩くだけで分割された7z+インストーラができるようになっていると非常に嬉しいです。pythonでsplitする方法だとpythonのインストールが必要になって少し大変かもなので、linuxのsplitコマンドを用いる手もあるかもしれません。
3. 2に加えてpublishまで1コマンドで実行できると更に嬉しいです。公開までの手順が多いのでなるべく減らせると嬉しいのと、おそらくとても詳しくなっているHyodaKazuakiさんにお任せするのが最適解なのと、将来actionsでリリースする素晴らしい環境の布石になるのとで、非常に魅力的だと感じています。

2021-08-16 12:08 UTC, HyodaKazuaki commented
ご確認いただけたようで何よりです。

要望についていくつか確認したいことがあります。

> 1. テストが通るようになっていることは必須です。

以下のワークフローを見たところ、ビルドできるかがテストになっていることを確認しました。
https://github.com/Hiroshiba/voicevox/blob/784128db3e2bb41df08c31155c4776ec138c059a/.github/workflows/test.yml
ただ単にLinuxでビルドできるようにするのであれば、`vue.config.js`にlinuxの項目を追加すれば対応できるかと思います。

しかし、このテストの意義は「Windows向けにビルドできるか」にあると推量しました。
そこで、以下の2つのどちらかの方法を取ることがより良いかと思います。
* ワークフローのターゲット(`runs-on`)を`ubuntu-latest`から`windows-latest`に変更し、Windows環境でビルド/テストする
* `electronuserland/builder:wine-chrome`Dockerイメージをワークフローで呼び出し、Linux上でWindows向けアプリをビルド/テストする

> 2. electron:buildを叩くだけで分割された7z+インストーラを生成できるようになっていると非常に嬉しいです。

Linuxコマンドでファイルを分割する方法は当初検討したのですが、現時点ではWindows環境下でしかビルド/実行できないことからPythonスクリプトを採用しました。
調べたところ、ファイル分割スクリプトを以下のように組み込めば`electron:build`コマンドだけでビルドから分割までできる可能性があります。
1. JavaScriptでファイルを分割するスクリプトを作成する
2. electron-builderの`afterAllArtifactBuild` hookに1のスクリプトを指定する
3. `npm run electron:build`を実行する

実際に分割できるか検証していませんので、後ほど確認してこのPRに追加します。

> 3. 2に加えてpublishまで1コマンドで実行できると更に嬉しいです。

この件は私も同意します。ただ、当面はビルドと分割までを1コマンドで実現できることを目標にしたいと思います。
分割したファイルをelectron-builderでpublishできるか不明なためです。
リリースノートの記載も自動化できない可能性があるため、GitHub Actionsと組み合わせるほうがいいかもしれません。

2021-08-16 13:38 UTC, Hiroshiba commented
1. たしかにwindows環境でビルドできることが大切だと思います。wineを用いるよりは、windows-latestを使うほうが良さそうに感じました。windowsサーバーらしいので少し勝手が違うかもしれませんが、一度`windows-latest`を使ってみましょう。
2. たしかにwindows環境だとsplitコマンドが無いかもしれません。Node.js製にできるのが一番クールだと思うので、ぜひそちらの方針でお願いします。
3. そうですね、publishに関してはあとあと検討で全然良いと思います。

2021-08-16 17:12 UTC, HyodaKazuaki commented
> 1. たしかにwindows環境でビルドできることが大切だと思います。wineを用いるよりは、windows-latestを使うほうが良さそうに感じました。windowsサーバーらしいので少し勝手が違うかもしれませんが、一度windows-latestを使ってみましょう。

8c9757c でOSの差し替えを行いました。

> 2. たしかにwindows環境だとsplitコマンドが無いかもしれません。Node.js製にできるのが一番クールだと思うので、ぜひそちらの方針でお願いします。

83206f3 で分割スクリプトとそれをhookするコードを追加しました。
JavaScriptが不慣れなものであまりいいコードではないかと思います。不都合な点などあればご指摘ください。

2021-08-16 18:58 UTC, Hiroshiba requested changes
TypeScript化できると良さそうなんですが、コンパイルとかの設定方法がよくわからなくて手がつけられませんね・・・。

テストも通っていそうですね！
https://github.com/Hiroshiba/voicevox/pull/95/checks?check_run_id=3343065958#step:11:246

2021-08-16 18:58 UTC, Hiroshiba commented on splitResources.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
用途がわかるように、`build`ディレクトリにこのファイルを配置するのはどうでしょう。

2021-08-16 18:58 UTC, Hiroshiba commented on splitResources.js
> +const path = require("path");
自分もよくjs/tsを知らないのですが、このように書くとその上のdisable文を失くせるかもしれません。
https://github.com/Hiroshiba/voicevox/blob/630569e2f46da1956eef35278cc40ee8c3b24495/src/background.ts#L12

2021-08-16 18:58 UTC, Hiroshiba commented on splitResources.js
> +  const fileName = "voicevox-0.3.1-x64.nsis.7z"; // targe file name
バージョンがマジックナンバーになっているので、なんかしらの方法で得られると良さそうです

2021-08-16 18:58 UTC, Hiroshiba commented on splitResources.js
> +  const targetDirectory = path.resolve(buildResult["outDir"], "nsis-web"); // for nsis-web
こっちの書き方が一般的かもしれません
```suggestion
  const targetDirectory = path.resolve(buildResult.outDir, "nsis-web"); // for nsis-web
```

2021-08-16 18:58 UTC, Hiroshiba commented on splitResources.js
> +  let file_index = 0;
細かいですが、camelCaseが一般的です
```suggestion
  let fileIndex = 0;
```

2021-08-17 05:38 UTC, HyodaKazuaki commented on splitResources.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
そうですね、その方がわかりやすそうです。

e4e2be2 と 28c4ad0 で対応しました。

2021-08-17 05:40 UTC, HyodaKazuaki commented on splitResources.js
> +  const fileName = "voicevox-0.3.1-x64.nsis.7z"; // targe file name
electron-builderのhookで与えられる引数にプロジェクトのバージョン情報がなかったため、環境変数`process.env.npm_package_version`からバージョンを取得するようにしました。 1f1472c

2021-08-17 06:10 UTC, HyodaKazuaki commented on splitResources.js
> +  const fileName = "voicevox-0.3.1-x64.nsis.7z"; // targe file name
electron-builderのhookで与えられる引数にプロジェクトのバージョン情報がなかったため、環境変数`process.env.npm_package_version`からバージョンを取得するようにしました。 1f1472c 5b93324

2021-08-17 06:10 UTC, HyodaKazuaki commented on splitResources.js
> +  let file_index = 0;
7c12da2 で対応しました。

2021-08-17 06:15 UTC, HyodaKazuaki commented on splitResources.js
> +const path = require("path");
この書き方ですが、JavaScriptで可能でしょうか？
pathやfsがTypeScriptのモジュールであるためか、実行することができませんでした。
```
voicevox\build\splitResources.js:1
import fs from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

`vue.config.js`でも同じ書き方をしているので、eslint抑制用のコメントを以下のもの(ファイル内でのrequireを容認する)に変更するのはいかがでしょうか。
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const fs = require("fs");
const path = require("path");
```

2021-08-17 14:50 UTC, HyodaKazuaki commented
https://github.com/Hiroshiba/voicevox/pull/95#discussion_r690065299

こちらの件についてご意見をいただけますか？

2021-08-17 17:16 UTC, Hiroshiba commented on splitResources.js
> +const path = require("path");
新しいバージョンのjavascriptならimportの書き方ができるはずなのですが、設定方法がわからないんですよね・・・。
なので、いったんそちらの書き方で良いと思います。

2021-08-17 17:20 UTC, HyodaKazuaki commented on splitResources.js
> +const path = require("path");
確認いただきありがとうございます。
c5c5522 で不使用の変数に対するもの含め修正しました。

2021-08-17 17:39 UTC, HyodaKazuaki commented
ご指摘の箇所の修正が終わりましたので、再度レビューをお願いします。

2021-08-17 17:55 UTC, Hiroshiba approved these changes
LGTM！　これでインストーラーとして配布できるかもしれません、とても嬉しいです。
実際のVOICEVOXでちゃんとビルドできるかは、バージョンアップのときに試してみたいと思います。

2021-08-17 17:55 UTC, Hiroshiba commented on vue.config.js
> +        extends: null,
後学のために知りたいのですが、extendsをnullにする理由はあったりしますか？

2021-08-17 18:22 UTC, HyodaKazuaki commented on vue.config.js
> +        extends: null,
> The name of a built-in configuration preset or path to config file (relative to project dir). Currently, only react-cra is supported.
> 
> If react-scripts in the app dependencies, react-cra will be set automatically. Set to null to disable automatic detection.

[electron-builder](https://www.electron.build/configuration/configuration.html)より

react-cra(reactのビルドなどを行うコマンド)の設定ファイルを指定できるようになっているようです。
未定義の場合、`react-scripts`がプロジェクトに入っていればreact-craの設定を探して当てはめてくれるようになっています。

このプロジェクトでは`react-scripts`が入っていないのでnullでも未定義でも動作にはほとんど差はないかと思います。
ただ、nullだと「`react-scripts`が入っているため意図的に無視させている」という意味合いを強く感じます。
ですので、この項目は除去します。

2021-08-17 18:32 UTC, Hiroshiba commented on vue.config.js
> +        extends: null,
なるほどです。ありがとうございます。

2021-08-17 18:39 UTC, Hiroshiba commented
テストが通っていそうなのでマージします。

2021-08-17 18:39 UTC, merged